-- ============================================================
-- ORVIA · Live-Schema-Abgleich  (ERZEUGT — nicht von Hand ändern)
-- Quelle: supabase/migrations/ (36 Dateien)
-- Neu erzeugen: node app/tools/gen-live-check.mjs
-- ============================================================
-- Diese Abfrage beantwortet die eine Frage, die `public.schema_migrations`
-- nicht beantworten kann: Ist das, was die Migrationsdateien anlegen, in DIESER
-- Instanz wirklich vorhanden?
--
-- Ergebnis lesen: JEDE zurückgegebene Zeile FEHLT in der Datenbank.
-- Leeres Ergebnis = Migrationsdateien und Instanz sind deckungsgleich.
-- Nur Lesezugriffe.
--
-- Umfang: 50 Tabellen + 63 Spalten + 62 Indizes + 19 RLS = 194 Prüfungen.
-- 'rls' prüft, dass row level security auf der Tabelle AKTIV ist (aus = offener Zugriff).
-- Bewusst NICHT geprüft: einzelne Policies, Constraints-Definitionen, Funktionen, Grants.
-- ============================================================

with erwartet(migration, art, tabelle, spalte) as (values
  ('0009','tabelle','activities',''),
  ('0019','tabelle','connected_devices',''),
  ('0002','tabelle','daily_checkins',''),
  ('0019','tabelle','daily_energy_expenditure',''),
  ('0019','tabelle','data_providers',''),
  ('0019','tabelle','device_capabilities',''),
  ('0032','tabelle','engine_decision_log',''),
  ('0003','tabelle','equipment',''),
  ('0003','tabelle','exercise_alternatives',''),
  ('0003','tabelle','exercise_equipment',''),
  ('0003','tabelle','exercise_muscles',''),
  ('0003','tabelle','exercise_training_qualities',''),
  ('0003','tabelle','exercises',''),
  ('0002','tabelle','fixed_schedule_items',''),
  ('0037','tabelle','goal_shadow_log',''),
  ('0019','tabelle','metric_anomalies',''),
  ('0003','tabelle','movement_patterns',''),
  ('0003','tabelle','muscle_groups',''),
  ('0036','tabelle','oauth_tokens',''),
  ('0002','tabelle','orvia_migrations',''),
  ('0019','tabelle','profile_metric_settings',''),
  ('0036','tabelle','profiles',''),
  ('0019','tabelle','provider_credentials',''),
  ('0002','tabelle','readiness_baselines',''),
  ('0002','tabelle','readiness_components',''),
  ('0002','tabelle','readiness_scores',''),
  ('0002','tabelle','schema_migrations',''),
  ('0003','tabelle','sport_positions',''),
  ('0003','tabelle','sports',''),
  ('0035','tabelle','strength_workout_exports',''),
  ('0002','tabelle','training_load_daily',''),
  ('0003','tabelle','training_plan_days',''),
  ('0003','tabelle','training_plan_exercises',''),
  ('0003','tabelle','training_qualities',''),
  ('0014','tabelle','user_constraints',''),
  ('0031','tabelle','user_feature_flags',''),
  ('0002','tabelle','user_goals',''),
  ('0028','tabelle','user_metric_series',''),
  ('0019','tabelle','user_metrics',''),
  ('0002','tabelle','user_profiles',''),
  ('0002','tabelle','user_sports',''),
  ('0003','tabelle','user_training_plans',''),
  ('0030','tabelle','user_week_plans',''),
  ('0002','tabelle','weekly_availability',''),
  ('0003','tabelle','workout_exercises',''),
  ('0003','tabelle','workout_sessions',''),
  ('0003','tabelle','workout_sets',''),
  ('0003','tabelle','workout_template_days',''),
  ('0003','tabelle','workout_template_exercises',''),
  ('0003','tabelle','workout_templates',''),
  ('0021','spalte','daily_checkins','auto_sources'),
  ('0015','spalte','daily_checkins','energy'),
  ('0015','spalte','daily_checkins','note'),
  ('0024','spalte','daily_checkins','red_flags'),
  ('0002','spalte','training_load_daily','client_session_id'),
  ('0035','spalte','training_plan_exercises','target_weight_kg'),
  ('0027','spalte','user_goals','category_data'),
  ('0002','spalte','user_goals','client_goal_id'),
  ('0003','spalte','user_goals','current_value'),
  ('0027','spalte','user_goals','custom_category'),
  ('0012','spalte','user_goals','description'),
  ('0003','spalte','user_goals','gym_goal_type'),
  ('0012','spalte','user_goals','metric_type'),
  ('0027','spalte','user_goals','milestones'),
  ('0027','spalte','user_goals','motivation'),
  ('0003','spalte','user_goals','position_key'),
  ('0012','spalte','user_goals','section_updated_at'),
  ('0003','spalte','user_goals','sport_key'),
  ('0027','spalte','user_goals','sports'),
  ('0003','spalte','user_goals','start_date'),
  ('0027','spalte','user_goals','time_horizon'),
  ('0002','spalte','user_profiles','age_estimate'),
  ('0016','spalte','user_profiles','avatar_path'),
  ('0029','spalte','user_profiles','bio'),
  ('0002','spalte','user_profiles','birth_date'),
  ('0013','spalte','user_profiles','constraints_acknowledged_at'),
  ('0029','spalte','user_profiles','handle'),
  ('0016','spalte','user_profiles','location'),
  ('0018','spalte','user_profiles','preferences'),
  ('0018','spalte','user_profiles','recovery'),
  ('0011','spalte','user_sports','client_role'),
  ('0011','spalte','user_sports','custom_name'),
  ('0003','spalte','user_sports','custom_position'),
  ('0003','spalte','user_sports','level'),
  ('0003','spalte','user_sports','position_key'),
  ('0003','spalte','user_sports','season_phase'),
  ('0011','spalte','user_sports','section_updated_at'),
  ('0011','spalte','user_sports','sessions_per_week'),
  ('0003','spalte','user_sports','sport_key'),
  ('0011','spalte','user_sports','typical_duration_min'),
  ('0013','spalte','weekly_availability','max_intense_week'),
  ('0013','spalte','weekly_availability','max_sessions_week'),
  ('0013','spalte','weekly_availability','min_rest_days'),
  ('0013','spalte','weekly_availability','rest_day'),
  ('0013','spalte','weekly_availability','section_updated_at'),
  ('0004','spalte','workout_exercises','client_exercise_id'),
  ('0035','spalte','workout_exercises','target_weight_kg'),
  ('0004','spalte','workout_sessions','cancel_reason'),
  ('0005','spalte','workout_sessions','paused_at'),
  ('0004','spalte','workout_sessions','perceived_effort'),
  ('0025','spalte','workout_sessions','planned_session_snapshot'),
  ('0004','spalte','workout_sessions','session_rpe'),
  ('0003','spalte','workout_sessions','sport_key'),
  ('0005','spalte','workout_sessions','total_paused_seconds'),
  ('0004','spalte','workout_sets','client_set_id'),
  ('0035','spalte','workout_sets','external_set_key'),
  ('0035','spalte','workout_sets','garmin_category_raw'),
  ('0035','spalte','workout_sets','garmin_exercise_name_raw'),
  ('0035','spalte','workout_sets','import_status'),
  ('0035','spalte','workout_sets','imported_at'),
  ('0035','spalte','workout_sets','recognition_probability'),
  ('0035','spalte','workout_sets','source'),
  ('0035','spalte','workout_sets','wkt_step_index'),
  ('0009','index','activities_client_uniq',''),
  ('0009','index','activities_source_uniq',''),
  ('0009','index','activities_user_started_idx',''),
  ('0009','index','activities_workout_uniq',''),
  ('0019','index','connected_devices_uniq',''),
  ('0017','index','daily_checkins_type_uniq',''),
  ('0002','index','daily_checkins_user_date_idx',''),
  ('0019','index','daily_energy_expenditure_uniq',''),
  ('0019','index','data_providers_user_type_uniq',''),
  ('0022','index','dee_user_date_idx',''),
  ('0019','index','device_capabilities_uniq',''),
  ('0032','index','engine_decision_log_parent_idx',''),
  ('0033','index','engine_decision_log_type_idx',''),
  ('0032','index','engine_decision_log_user_idx',''),
  ('0032','index','engine_decision_log_week_idx',''),
  ('0008','index','exercise_muscles_uniq',''),
  ('0003','index','exercises_system_idx',''),
  ('0003','index','exercises_user_idx',''),
  ('0002','index','fixed_schedule_user_idx',''),
  ('0037','index','goal_shadow_log_user_time_idx',''),
  ('0019','index','metric_anomalies_open_idx',''),
  ('0019','index','profile_metric_settings_uniq',''),
  ('0019','index','provider_credentials_uniq',''),
  ('0017','index','readiness_baselines_metric_uniq',''),
  ('0002','index','readiness_components_score_idx',''),
  ('0002','index','readiness_components_user_idx',''),
  ('0017','index','readiness_scores_day_uniq',''),
  ('0002','index','readiness_scores_user_date_idx',''),
  ('0035','index','swe_activity_idx',''),
  ('0035','index','swe_garmin_workout_uniq',''),
  ('0035','index','swe_occurrence_idx',''),
  ('0002','index','training_load_client_uniq',''),
  ('0002','index','training_load_ext_uniq',''),
  ('0002','index','training_load_user_date_idx',''),
  ('0028','index','ums_user_metric_date_idx',''),
  ('0014','index','user_constraints_client_uniq',''),
  ('0014','index','user_constraints_user_idx',''),
  ('0031','index','user_feature_flags_flag_idx',''),
  ('0031','index','user_feature_flags_user_idx',''),
  ('0002','index','user_goals_client_uniq',''),
  ('0002','index','user_goals_user_idx',''),
  ('0019','index','user_metrics_date_idx',''),
  ('0019','index','user_metrics_lookup_idx',''),
  ('0019','index','user_metrics_source_record_uniq',''),
  ('0002','index','user_sports_uniq',''),
  ('0003','index','user_training_plans_user_idx',''),
  ('0030','index','uwp_user_week_idx',''),
  ('0002','index','weekly_availability_uniq',''),
  ('0004','index','workout_exercises_client_uniq',''),
  ('0003','index','workout_exercises_session_idx',''),
  ('0003','index','workout_exercises_uniq',''),
  ('0004','index','workout_exercises_user_idx',''),
  ('0003','index','workout_sessions_client_uniq',''),
  ('0004','index','workout_sessions_one_active',''),
  ('0004','index','workout_sessions_status_idx',''),
  ('0003','index','workout_sessions_user_date_idx',''),
  ('0004','index','workout_sets_client_uniq',''),
  ('0003','index','workout_sets_exercise_idx',''),
  ('0035','index','workout_sets_external_uniq',''),
  ('0035','index','workout_sets_import_status_idx',''),
  ('0003','index','workout_sets_uniq',''),
  ('0004','index','workout_sets_user_idx',''),
  ('0009','rls','activities',''),
  ('0022','rls','daily_energy_expenditure',''),
  ('0032','rls','engine_decision_log',''),
  ('0003','rls','exercise_alternatives',''),
  ('0003','rls','exercises',''),
  ('0037','rls','goal_shadow_log',''),
  ('0036','rls','oauth_tokens',''),
  ('0036','rls','profiles',''),
  ('0002','rls','readiness_components',''),
  ('0036','rls','schema_migrations',''),
  ('0035','rls','strength_workout_exports',''),
  ('0014','rls','user_constraints',''),
  ('0031','rls','user_feature_flags',''),
  ('0028','rls','user_metric_series',''),
  ('0016','rls','user_profiles',''),
  ('0030','rls','user_week_plans',''),
  ('0003','rls','workout_template_days',''),
  ('0003','rls','workout_template_exercises',''),
  ('0003','rls','workout_templates','')
)
select e.migration, e.art, e.tabelle, e.spalte
  from erwartet e
 where (e.art = 'tabelle' and not exists (
         select 1 from information_schema.tables t
          where t.table_schema='public' and t.table_name = e.tabelle))
    or (e.art = 'spalte' and not exists (
         select 1 from information_schema.columns c
          where c.table_schema='public' and c.table_name = e.tabelle
            and c.column_name = e.spalte))
    or (e.art = 'index' and not exists (
         select 1 from pg_indexes i
          where i.schemaname='public' and i.indexname = e.tabelle))
    or (e.art = 'rls' and not exists (
         select 1 from pg_tables p
          where p.schemaname='public' and p.tablename = e.tabelle and p.rowsecurity = true))
 order by e.migration, e.tabelle, e.spalte;
