/* ============ SUPPLEMENT-DATEN (Lexikon-Inhalte, unveraendert aus v3) ============ */
const SUB_CATS={
  'Recovery & Gesundheit':['Magnesium','Omega-3 (EPA/DHA)','Vitamin D3','Vitamin K2','Zink','Vitamin C','Kollagen + Vit C','Curcumin','Tart Cherry','Kreatin','Whey/Protein','Casein','Multivitamin','Eisen','B12','Probiotika','CoQ10'],
  'Performance':['Koffein','Beta-Alanin','Citrullin-Malat','Rote-Bete/Nitrat','Natron (Bikarbonat)','Taurin','L-Carnitin','HMB','EAA/BCAA'],
  'Ausdauer / Fueling':['Kohlenhydrat-Gel','Maltodextrin','Elektrolyte/Natrium','Iso-Drink','Koffein-Gel'],
  'Schlaf & Stress':['Melatonin','Magnesium-Glycinat','L-Theanin','Glycin','Ashwagandha','Rhodiola','Apigenin']
};

const SUPP_INFO={
'Magnesium':{v:1,w:"Mineral für Muskel- und Nervenfunktion, Energiestoffwechsel und Schlaf.",e:"Mangel verschlechtert Leistung und Schlaf; Supplementierung wirkt v.a. bei Defizit.",d:"300–400mg/Tag, abends. Glycinat/Citrat besser verträglich als Oxid.",f:"Sinnvoll – Ausdauertraining und Schwitzen erhöhen den Bedarf, unterstützt Schlaf und Muskelregeneration. Glycinat-Form abends ideal."},
'Omega-3 (EPA/DHA)':{v:1,w:"Entzündungsmodulierende Fettsäuren für Herz, Hirn und Regeneration.",e:"Solide für Entzündung und Herzgesundheit, mögliche leichte Recovery-Vorteile.",d:"1–2g EPA+DHA/Tag zum Essen.",f:"Sinnvoll – dämpft die Entzündungslage an Sehnen und Gelenken (relevant bei Sehnenreizungen) und ist kardiovaskuläre Basis für Ausdauer. Bei wenig Fischkonsum supplementieren."},
'Vitamin D3':{v:1,w:"Hormon für Knochen, Immunsystem und Muskelfunktion.",e:"Mangel sehr verbreitet und leistungsmindernd.",d:"1000–4000 IE/Tag mit Fett, idealerweise mit K2.",f:"Sinnvoll, fast Pflicht – in nördlichen Breiten ist von Okt–März kaum Eigensynthese möglich. Wichtig für Knochen- und Sehnenheilung. Spiegel testen lassen."},
'Vitamin K2':{v:2,w:"Lenkt Kalzium in die Knochen statt in Arterien, Partner von D3.",e:"Plausibel für Knochen/Gefäße, Evidenz moderat.",d:"90–180µg MK-7/Tag mit D3.",f:"Situativ – sinnvolle Ergänzung, wenn du höher dosiertes D3 nimmst. Allein kein Muss."},
'Zink':{v:2,w:"Immunsystem, Hormonhaushalt, Wundheilung.",e:"Hilft bei Mangel, verkürzt evtl. Erkältungen.",d:"10–25mg/Tag, nicht dauerhaft hoch (Kupfer-Antagonist).",f:"Situativ – Schwitzen kostet Zink. Kurz bei Infektanzeichen, nicht dauerhaft hochdosiert."},
'Vitamin C':{v:2,w:"Antioxidans, Kofaktor der Kollagensynthese, Immunsystem.",e:"Gut für Immun bei Belastung; hohe Dauerdosen können Anpassung dämpfen.",d:"200–1000mg; chronisch nicht megadosieren.",f:"Situativ – wichtig als Kollagen-Kofaktor (siehe Kollagen). Nicht dauerhaft sehr hoch, das kann Trainingsanpassung bremsen."},
'Kollagen + Vit C':{v:1,w:"Kollagenpeptide plus Vitamin C liefern Bausteine für Sehnen und Bänder.",e:"Wachsende Evidenz: Sehnen-Kollagensynthese steigt, wenn 15g Kollagen + Vit C ~45–60min VOR dem Belastungsreiz genommen werden.",d:"15g Kollagen + ~50mg Vit C, ca. 1h vor der Reha-/Loading-Einheit.",f:"Dein klarster Neuzugang – direkt auf die Patellasehne gezielt. Timing ist entscheidend: vor dem Spanish-Squat-Reiz. Eine der wenigen sehnenwirksamen Maßnahmen mit Evidenz."},
'Curcumin':{v:2,w:"Entzündungshemmer aus Kurkuma.",e:"Moderate Evidenz für Muskelkater/Entzündung, bessere Aufnahme mit Piperin.",d:"500–1000mg standardisiert.",f:"Situativ – kann Tendinopathie-Entzündung und DOMS leicht dämpfen. Nice-to-have, kein Kern."},
'Tart Cherry':{v:2,w:"Sauerkirsch-Polyphenole, antioxidativ und leicht schlaffördernd.",e:"Reduziert Muskelkater/Marker nach intensiver Ausdauer, leichte Schlafvorteile.",d:"250–500ml Saft oder Extrakt um die Belastung/abends.",f:"Situativ – eher für intensive Renn-/Wettkampfphasen und Schlaf. In der Reha aktuell kein Kern."},
'Kreatin':{v:1,w:"Erhöht Phosphokreatin-Speicher: Kraft, Power, Muskelmasse, evtl. kognitiv.",e:"Eines der best-belegten Supplemente überhaupt, auch Ausdauer-Nebeneffekte.",d:"3–5g/Tag dauerhaft, Timing egal.",f:"Sinnvoll – günstig, sicher, unterstützt Kraft-/Reha-Arbeit und Muskelerhalt. Bindet ~0,3–0,5kg Wasser (im Gewicht-Chart einkalkulieren). Für deinen Lauf nicht nachteilig."},
'Whey/Protein':{v:1,w:"Schnelles Protein zum Erreichen der Tagesmenge und für Muskelproteinsynthese.",e:"Sehr gut belegt für Muskelaufbau und -erhalt.",d:"20–40g nach Training oder zum Auffüllen.",f:"Sinnvoll – dein Ziel 150–165g/Tag (~2g/kg) ist mit Vollkost allein schwer. Praktisches Werkzeug, kein Wundermittel."},
'Casein':{v:2,w:"Langsam verdauliches Protein für nächtliche Aminosäuren-Versorgung.",e:"Solide, minimal besser als Whey über Nacht.",d:"20–40g vor dem Schlaf.",f:"Situativ – abends ok für nächtliche Regeneration. Quark/Skyr erfüllen denselben Zweck günstiger."},
'Multivitamin':{v:2,w:"Breite Mikronährstoff-Absicherung.",e:"Kein Leistungsvorteil bei guter Ernährung, eher Lücken-Versicherung.",d:"1/Tag zum Essen.",f:"Situativ – bei deinem hohen Trainings-/Arbeitspensum als Absicherung ok, ersetzt aber keine gezielten Einzelstoffe (D3, Omega-3)."},
'Eisen':{v:2,w:"Sauerstofftransport via Hämoglobin, zentral für Ausdauer.",e:"Mangel ruiniert Ausdauerleistung; Supplement nur bei nachgewiesenem Defizit.",d:"Nur nach Ferritin-Bluttest, sonst Überladungsrisiko.",f:"Situativ und WICHTIG: Ausdauersportler haben erhöhtes Mangelrisiko. NICHT blind nehmen – lass Ferritin checken. Bei niedrigem Wert sehr wirksam, sonst schädlich."},
'B12':{v:2,w:"Blutbildung, Nerven, Energiestoffwechsel.",e:"Nur bei Mangel relevant (v.a. vegan/vegetarisch).",d:"Nach Bedarf.",f:"Situativ – nur falls du wenig tierische Produkte isst oder ein Mangel besteht. Sonst überflüssig."},
'Probiotika':{v:2,w:"Darmflora, evtl. Immun- und Magen-Darm-Unterstützung bei Belastung.",e:"Gemischt; manche Stämme reduzieren Infekte/GI-Probleme bei Ausdauer.",d:"Stammabhängig, regelmäßig.",f:"Situativ – interessant gegen Magen-Darm-Probleme bei langen IM-Einheiten. Aktuell kein Kern."},
'CoQ10':{v:3,w:"Mitochondrialer Elektronentransport, Antioxidans.",e:"Schwach für Leistung bei Gesunden.",d:"100–200mg.",f:"Wenig Nutzen – bei dir (22, gesund) kein erkennbarer Vorteil. Geld besser in D3/Omega-3."},
'Koffein':{v:1,w:"Zentrales Stimulans: Wachheit, geringeres Anstrengungsempfinden, mehr Leistung.",e:"Sehr gut belegt für Ausdauer UND Kraft/Power.",d:"3–6mg/kg ~45–60min vor Belastung (bei dir ~225–450mg).",f:"Sinnvoll als gezieltes Pre-Workout/Wettkampf-Tool. Toleranz steigt – nicht täglich maximal, für Schlüsseleinheiten/Rennen aufsparen. Nicht spät am Tag (Schlaf)."},
'Beta-Alanin':{v:2,w:"Erhöht Carnosin, puffert Säure bei 1–4min Maximalbelastung.",e:"Gut für hochintensive Intervalle.",d:"3–5g/Tag dauerhaft (Hautkribbeln normal).",f:"Situativ – erst relevant bei harten Lauf-/Rad-Intervallen. Für lange IM-Pace kaum Nutzen. Aktuell nicht nötig."},
'Citrullin-Malat':{v:2,w:"NO-Vorstufe: Durchblutung, evtl. Ausdauer/Pump, weniger Müdigkeit.",e:"Gemischt, einige Studien positiv.",d:"6–8g ~60min vor Training.",f:"Situativ – schwache Evidenz, kein Kern. Kannst du testen, niedrige Priorität."},
'Rote-Bete/Nitrat':{v:2,w:"Nitrat wird zu NO, verbessert die Sauerstoff-Ökonomie.",e:"Solide für Ausdauer-Ökonomie, v.a. submaximal.",d:"~6,4mmol Nitrat 2–3h vor Belastung.",f:"Situativ – kann bei HM/IM-Pace die Lauf-/Rad-Ökonomie leicht verbessern. Für Wettkampftage, nicht im Reha-Alltag."},
'Natron (Bikarbonat)':{v:2,w:"Extrazellulärer Puffer gegen Übersäuerung bei harter Belastung.",e:"Wirksam für 1–10min Maximalbelastung, GI-Probleme häufig.",d:"0,2–0,3g/kg, 60–180min vorher.",f:"Situativ – nur für sehr intensive kurze Belastungen. Für deine Ausdauerziele und aktuell irrelevant, Magen-Darm-Risiko."},
'Taurin':{v:3,w:"Aminosäure für Zellschutz und Elektrolythaushalt.",e:"Schwach/gemischt.",d:"1–3g.",f:"Wenig Nutzen – kein klarer Vorteil. Überspringen."},
'L-Carnitin':{v:3,w:"Transportiert Fettsäuren in die Mitochondrien.",e:"Schwach für Fettverbrennung/Leistung bei Gesunden.",d:"2–3g, lange Aufsättigung.",f:"Wenig Nutzen – die Marketing-Versprechen halten nicht. Nicht nötig."},
'HMB':{v:3,w:"Leucin-Metabolit, antikatabol.",e:"Allenfalls bei Untrainierten/Diätphasen, bei Trainierten kaum.",d:"3g/Tag.",f:"Wenig Nutzen – bei ausreichend Protein überflüssig. Sparen."},
'EAA/BCAA':{v:3,w:"Essenzielle Aminosäuren für Muskelproteinsynthese.",e:"BCAA allein unterlegen vs. komplettes Protein, EAA ok bei Mangel.",d:"Situativ.",f:"Wenig Nutzen – bei deiner hohen Proteinzufuhr (Whey/Vollkost) redundant. Lieber komplettes Protein essen/trinken."},
'Kohlenhydrat-Gel':{v:2,w:"Schnelle Kohlenhydrate während der Belastung.",e:"Sehr gut belegt für Ausdauer >60–90min.",d:"30–90g KH/h, Darm trainieren.",f:"Situativ, später wichtig: für lange Rad-/Lauf-Einheiten Richtung 70.3/IM. Darm ans Fueling gewöhnen. Aktuell bei kurzen Einheiten unnötig."},
'Maltodextrin':{v:2,w:"Günstige, schnelle Kohlenhydratquelle als Pulver.",e:"Wie Gels, Fueling-Basis.",d:"In der Flasche, 30–60g/h.",f:"Situativ – kostengünstige Eigen-Mix-Variante fürs IM-Fueling. Später relevant."},
'Elektrolyte/Natrium':{v:2,w:"Ersetzt Schweißverluste (v.a. Natrium), beugt Krämpfen/Hyponatriämie vor.",e:"Wichtig bei langen/heißen Einheiten.",d:"300–800mg Natrium/h je nach Schweißrate.",f:"Situativ – bei langen Einheiten/Hitze relevant, besonders IM. Bei kurzen Sessions reicht Wasser."},
'Iso-Drink':{v:2,w:"Kombi aus Kohlenhydraten, Elektrolyten und Flüssigkeit.",e:"Praktisch fürs gleichzeitige Fueling und Hydration.",d:"Während längerer Belastung.",f:"Situativ – bequemes All-in-One für lange Einheiten/Wettkampf. Aktuell kein Bedarf."},
'Koffein-Gel':{v:2,w:"Kohlenhydrate plus Koffein-Boost spät im Rennen.",e:"Koffein-Effekt gut belegt.",d:"Ein Gel mit ~50–100mg Koffein in der zweiten Renn-Hälfte.",f:"Situativ – reines Renn-Tool für die HM/IM-Endphase. Nichts für den Alltag."},
'Melatonin':{v:2,w:"Schlafhormon, verkürzt Einschlafzeit und hilft bei Rhythmus-Verschiebung.",e:"Gut für Einschlaflatenz und Jetlag, niedrige Dosis reicht.",d:"0,5–1mg ~30–60min vor dem Schlaf (mehr ist nicht besser).",f:"Du nimmst es. Hinweis: niedrig dosieren (0,5–1mg) – hohe Dosen bringen Hangover ohne Mehrwert. Besonders sinnvoll bei frühen Schwimm-Tagen/verschobenem Rhythmus, nicht zwingend jede Nacht."},
'Magnesium-Glycinat':{v:1,w:"Gut bioverfügbare, magenfreundliche Magnesiumform, beruhigend.",e:"Wie Magnesium, Glycinat-Form schlaf- und entspannungsfreundlich.",d:"200–400mg elementar abends.",f:"Sinnvoll – die beste Form für dein abendliches Magnesium (Schlaf + Muskel). Ersetzt dein normales Magnesium, nicht zusätzlich."},
'L-Theanin':{v:2,w:"Aminosäure aus Tee, fördert ruhige Wachheit und dämpft Koffein-Nervosität.",e:"Solide für Entspannung/Fokus, oft mit Koffein kombiniert.",d:"100–200mg.",f:"Situativ – gut gegen Koffein-Zappeligkeit oder zum Runterkommen abends. Nice-to-have."},
'Glycin':{v:2,w:"Aminosäure, senkt die Körperkerntemperatur und verbessert Schlafqualität.",e:"Kleine Studien zeigen bessere subjektive Schlafqualität.",d:"3g vor dem Schlaf.",f:"Situativ – günstige, sichere Schlaf-Ergänzung, kombinierbar mit Magnesium-Glycinat. Test wert, wenn die Schlafqualität schwankt."},
'Ashwagandha':{v:2,w:"Adaptogen, senkt Cortisol/Stress, evtl. Kraft/Recovery.",e:"Moderat für Stress/Schlaf, einige Kraft-/VO2-Studien positiv.",d:"300–600mg Extrakt (z.B. KSM-66).",f:"Situativ – interessant bei deiner Doppelbelastung (50h Arbeit + 15h Sport) für Stress und Schlaf. Zyklisch nehmen, nicht endlos."},
'Rhodiola':{v:2,w:"Adaptogen gegen mentale und körperliche Ermüdung.",e:"Gemischt, einige Anti-Fatigue-Effekte.",d:"200–400mg standardisiert.",f:"Situativ – schwächere Evidenz als Ashwagandha. Niedrige Priorität, eher gegen mentale Müdigkeit."},
'Apigenin':{v:3,w:"Pflanzenstoff (u.a. aus Kamille), leicht beruhigend.",e:"Schwach, meist Tier-/Anekdotendaten.",d:"~50mg abends.",f:"Wenig Nutzen – kaum Humanevidenz. Kamillentee tut es auch. Überspringen."}
};

function vmeta(v){return v===1?{c:'s1',t:'Sinnvoll für dich'}:v===2?{c:'s2',t:'Situativ'}:{c:'s3',t:'Wenig Nutzen'};}
