-- ============================================================
--  ORVIA · 0006 — Übungsbibliothek-Erweiterung (Phase 4.2e)
--  Ergänzt die ~20 Minimal-Seeds (0003) auf ~79 Systemübungen mit korrekten
--  Bewegungsmustern, primären/sekundären Muskeln und Equipment.
--  Idempotent (on conflict do nothing), löscht nichts, keine neuen Spalten.
--  Nutzt vorhandene Tabellen: exercises, exercise_muscles (muscle_key→muscle_groups),
--  exercise_equipment (equipment_key→equipment). Stabile Slugs als eindeutiger Schlüssel.
-- ============================================================

-- 0) Neue Bewegungsmuster konsistent registrieren (von Beinstrecker/Adduktoren/Abduktoren genutzt).
--    movement_pattern in exercises ist nur lose gekoppelt — diese Einträge halten die Domäne sauber.
insert into public.movement_patterns (key, name) values
 ('knee_extension','Beinstreckung'),
 ('hip_adduction','Adduktion'),
 ('hip_abduction','Abduktion')
on conflict (key) do update set name = excluded.name;

insert into public.exercises (slug, is_system, name, category, movement_pattern, difficulty, unilateral, bodyweight) values
 -- Brust
 ('db_bench_press',true,'Kurzhantel-Bankdrücken','compound','horizontal_push','beginner',false,false),
 ('db_incline_press',true,'Kurzhantel-Schrägbankdrücken','compound','horizontal_push','beginner',false,false),
 ('chest_press_machine',true,'Brustpresse Maschine','compound','horizontal_push','beginner',false,false),
 ('cable_chest_press',true,'Brustpresse Kabel','compound','horizontal_push','beginner',false,false),
 ('cable_fly',true,'Kabel-Flys','isolation','horizontal_push','beginner',false,false),
 ('pec_deck',true,'Butterfly / Pec Deck','isolation','horizontal_push','beginner',false,false),
 ('pushup',true,'Liegestütze','compound','horizontal_push','beginner',false,true),
 ('chest_dip',true,'Dips (brustbetont)','compound','vertical_push','intermediate',false,true),
 -- Rücken
 ('chinup',true,'Chin-ups','compound','vertical_pull','advanced',false,true),
 ('lat_pulldown_neutral',true,'Latzug neutral','compound','vertical_pull','beginner',false,false),
 ('lat_pulldown_single',true,'Latzug einarmig','compound','vertical_pull','beginner',true,false),
 ('barbell_row',true,'Langhantelrudern','compound','horizontal_pull','intermediate',false,false),
 ('db_row',true,'Kurzhantelrudern','compound','horizontal_pull','beginner',true,false),
 ('cable_row',true,'Kabelrudern','compound','horizontal_pull','beginner',false,false),
 ('chest_supported_row',true,'Brustgestütztes Rudern','compound','horizontal_pull','beginner',false,false),
 ('row_machine',true,'Rudermaschine','compound','horizontal_pull','beginner',false,false),
 ('straight_arm_pulldown',true,'Straight-Arm Pulldown','isolation','shoulder_extension','beginner',false,false),
 ('face_pull',true,'Face Pulls','isolation','horizontal_pull','beginner',false,false),
 -- Schultern
 ('db_shoulder_press',true,'Schulterdrücken Kurzhantel','compound','vertical_push','beginner',false,false),
 ('shoulder_press_machine',true,'Schulterpresse Maschine','compound','vertical_push','beginner',false,false),
 ('cable_lateral_raise',true,'Seitheben Kabel','isolation','shoulder_abduction','beginner',true,false),
 ('machine_lateral_raise',true,'Seitheben Maschine','isolation','shoulder_abduction','beginner',false,false),
 ('reverse_fly',true,'Reverse Flys','isolation','horizontal_pull','beginner',false,false),
 ('reverse_pec_deck',true,'Reverse Pec Deck','isolation','horizontal_pull','beginner',false,false),
 ('rear_delt_cable',true,'Rear-Delt Kabelzug','isolation','horizontal_pull','beginner',true,false),
 -- Beine & Gesäß
 ('front_squat',true,'Frontkniebeuge','compound','squat','advanced',false,false),
 ('hack_squat',true,'Hackenschmidt-Kniebeuge','compound','squat','intermediate',false,false),
 ('step_up',true,'Step-ups','compound','lunge','beginner',true,false),
 ('walking_lunge',true,'Ausfallschritte gehend','compound','lunge','beginner',true,false),
 ('reverse_lunge',true,'Ausfallschritte rückwärts','compound','lunge','beginner',true,false),
 ('deadlift',true,'Kreuzheben','compound','hinge','advanced',false,false),
 ('glute_bridge',true,'Glute Bridge','compound','hip_extension','beginner',false,true),
 ('seated_leg_curl',true,'Beinbeuger sitzend','isolation','knee_flexion','beginner',false,false),
 ('lying_leg_curl',true,'Beinbeuger liegend','isolation','knee_flexion','beginner',false,false),
 ('leg_extension',true,'Beinstrecker','isolation','knee_extension','beginner',false,false),
 ('adductor_machine',true,'Adduktorenmaschine','isolation','hip_adduction','beginner',false,false),
 ('abductor_machine',true,'Abduktorenmaschine','isolation','hip_abduction','beginner',false,false),
 ('standing_calf_raise',true,'Wadenheben stehend','isolation','calf','beginner',false,false),
 ('seated_calf_raise',true,'Wadenheben sitzend','isolation','calf','beginner',false,false),
 -- Bizeps & Trizeps
 ('barbell_curl',true,'Langhantelcurls','isolation','elbow_flexion','beginner',false,false),
 ('db_curl',true,'Kurzhantelcurls','isolation','elbow_flexion','beginner',false,false),
 ('hammer_curl',true,'Hammercurls','isolation','elbow_flexion','beginner',false,false),
 ('incline_curl',true,'Schrägbankcurls','isolation','elbow_flexion','beginner',false,false),
 ('cable_curl',true,'Kabelcurls','isolation','elbow_flexion','beginner',false,false),
 ('preacher_curl',true,'Preacher Curls','isolation','elbow_flexion','beginner',false,false),
 ('rope_pushdown',true,'Trizepsdrücken Seil','isolation','elbow_extension','beginner',false,false),
 ('overhead_triceps',true,'Überkopf-Trizeps Kabel','isolation','elbow_extension','beginner',false,false),
 ('skull_crusher',true,'Skull Crusher','isolation','elbow_extension','intermediate',false,false),
 ('close_grip_bench',true,'Enges Bankdrücken','compound','elbow_extension','intermediate',false,false),
 ('triceps_dip',true,'Dips (trizepsbetont)','compound','elbow_extension','intermediate',false,true),
 -- Core & Rumpf
 ('cable_crunch',true,'Cable Crunch','isolation','trunk_flexion','beginner',false,false),
 ('crunch',true,'Crunch','isolation','trunk_flexion','beginner',false,true),
 ('hanging_leg_raise',true,'Hanging Leg Raise','isolation','trunk_flexion','intermediate',false,true),
 ('lying_leg_raise',true,'Beinheben liegend','isolation','trunk_flexion','beginner',false,true),
 ('ab_wheel',true,'Ab Wheel','isolation','anti_rotation','intermediate',false,true),
 ('side_plank',true,'Side Plank','isolation','anti_rotation','beginner',true,true),
 ('pallof_press',true,'Pallof Press','isolation','anti_rotation','beginner',false,false),
 ('back_extension',true,'Rückenstrecker','isolation','trunk_extension','beginner',false,false),
 ('farmer_carry',true,'Farmer''s Carry','compound','carry','beginner',false,false)
on conflict (slug) do nothing;

-- Muskelzuordnung (direkt = primär, indirect = sekundär). Summen müssen nicht 1.0 sein.
insert into public.exercise_muscles (exercise_id, muscle_key, weight, involvement)
 select e.id, v.mk, v.w, v.inv from public.exercises e join (values
  ('db_bench_press','chest',1.0,'direct'),('db_bench_press','triceps',0.5,'indirect'),('db_bench_press','front_delts',0.4,'indirect'),
  ('db_incline_press','chest',1.0,'direct'),('db_incline_press','front_delts',0.5,'indirect'),('db_incline_press','triceps',0.4,'indirect'),
  ('chest_press_machine','chest',1.0,'direct'),('chest_press_machine','triceps',0.4,'indirect'),
  ('cable_chest_press','chest',1.0,'direct'),('cable_chest_press','front_delts',0.4,'indirect'),
  ('cable_fly','chest',1.0,'direct'),('cable_fly','front_delts',0.3,'indirect'),
  ('pec_deck','chest',1.0,'direct'),
  ('pushup','chest',1.0,'direct'),('pushup','triceps',0.5,'indirect'),('pushup','abs',0.3,'indirect'),
  ('chest_dip','chest',1.0,'direct'),('chest_dip','triceps',0.6,'indirect'),('chest_dip','front_delts',0.4,'indirect'),
  ('chinup','lats',1.0,'direct'),('chinup','biceps',0.6,'indirect'),('chinup','upper_back',0.4,'indirect'),
  ('lat_pulldown_neutral','lats',1.0,'direct'),('lat_pulldown_neutral','biceps',0.4,'indirect'),
  ('lat_pulldown_single','lats',1.0,'direct'),('lat_pulldown_single','biceps',0.4,'indirect'),
  ('barbell_row','upper_back',1.0,'direct'),('barbell_row','lats',0.6,'indirect'),('barbell_row','biceps',0.4,'indirect'),
  ('db_row','lats',1.0,'direct'),('db_row','upper_back',0.5,'indirect'),('db_row','biceps',0.4,'indirect'),
  ('cable_row','upper_back',1.0,'direct'),('cable_row','lats',0.5,'indirect'),('cable_row','biceps',0.4,'indirect'),
  ('chest_supported_row','upper_back',1.0,'direct'),('chest_supported_row','lats',0.5,'indirect'),
  ('row_machine','upper_back',1.0,'direct'),('row_machine','lats',0.5,'indirect'),
  ('straight_arm_pulldown','lats',1.0,'direct'),
  ('face_pull','rear_delts',1.0,'direct'),('face_pull','upper_back',0.5,'indirect'),('face_pull','traps',0.3,'indirect'),
  ('db_shoulder_press','front_delts',1.0,'direct'),('db_shoulder_press','side_delts',0.5,'indirect'),('db_shoulder_press','triceps',0.4,'indirect'),
  ('shoulder_press_machine','front_delts',1.0,'direct'),('shoulder_press_machine','triceps',0.4,'indirect'),
  ('cable_lateral_raise','side_delts',1.0,'direct'),
  ('machine_lateral_raise','side_delts',1.0,'direct'),
  ('reverse_fly','rear_delts',1.0,'direct'),('reverse_fly','upper_back',0.3,'indirect'),
  ('reverse_pec_deck','rear_delts',1.0,'direct'),('reverse_pec_deck','upper_back',0.3,'indirect'),
  ('rear_delt_cable','rear_delts',1.0,'direct'),
  ('front_squat','quads',1.0,'direct'),('front_squat','glutes',0.5,'indirect'),('front_squat','abs',0.3,'indirect'),
  ('hack_squat','quads',1.0,'direct'),('hack_squat','glutes',0.5,'indirect'),
  ('step_up','quads',1.0,'direct'),('step_up','glutes',0.6,'indirect'),('step_up','hamstrings',0.3,'indirect'),
  ('walking_lunge','quads',1.0,'direct'),('walking_lunge','glutes',0.6,'indirect'),
  ('reverse_lunge','glutes',1.0,'direct'),('reverse_lunge','quads',0.6,'indirect'),
  ('deadlift','glutes',1.0,'direct'),('deadlift','hamstrings',0.7,'indirect'),('deadlift','lower_back',0.6,'indirect'),
  ('glute_bridge','glutes',1.0,'direct'),('glute_bridge','hamstrings',0.4,'indirect'),
  ('seated_leg_curl','hamstrings',1.0,'direct'),
  ('lying_leg_curl','hamstrings',1.0,'direct'),
  ('leg_extension','quads',1.0,'direct'),
  ('adductor_machine','adductors',1.0,'direct'),
  ('abductor_machine','abductors',1.0,'direct'),
  ('standing_calf_raise','calves',1.0,'direct'),
  ('seated_calf_raise','calves',1.0,'direct'),
  ('barbell_curl','biceps',1.0,'direct'),('barbell_curl','forearms',0.3,'indirect'),
  ('db_curl','biceps',1.0,'direct'),
  ('hammer_curl','biceps',1.0,'direct'),('hammer_curl','forearms',0.5,'indirect'),
  ('incline_curl','biceps',1.0,'direct'),
  ('cable_curl','biceps',1.0,'direct'),
  ('preacher_curl','biceps',1.0,'direct'),
  ('rope_pushdown','triceps',1.0,'direct'),
  ('overhead_triceps','triceps',1.0,'direct'),
  ('skull_crusher','triceps',1.0,'direct'),
  ('close_grip_bench','triceps',1.0,'direct'),('close_grip_bench','chest',0.5,'indirect'),('close_grip_bench','front_delts',0.3,'indirect'),
  ('triceps_dip','triceps',1.0,'direct'),('triceps_dip','chest',0.4,'indirect'),
  ('cable_crunch','abs',1.0,'direct'),
  ('crunch','abs',1.0,'direct'),
  ('hanging_leg_raise','abs',1.0,'direct'),('hanging_leg_raise','hip_flexors',0.5,'indirect'),
  ('lying_leg_raise','abs',1.0,'direct'),('lying_leg_raise','hip_flexors',0.5,'indirect'),
  ('ab_wheel','abs',1.0,'direct'),('ab_wheel','lower_back',0.3,'indirect'),
  ('side_plank','abs',1.0,'direct'),
  ('pallof_press','abs',1.0,'direct'),
  ('back_extension','lower_back',1.0,'direct'),('back_extension','glutes',0.4,'indirect'),('back_extension','hamstrings',0.4,'indirect'),
  ('farmer_carry','forearms',1.0,'direct'),('farmer_carry','traps',0.5,'indirect'),('farmer_carry','abs',0.4,'indirect')
 ) as v(slug,mk,w,inv) on e.slug = v.slug
on conflict (exercise_id, muscle_key) do nothing;

-- Equipment-Zuordnung.
insert into public.exercise_equipment (exercise_id, equipment_key)
 select e.id, v.ek from public.exercises e join (values
  ('db_bench_press','dumbbell'),('db_bench_press','bench'),
  ('db_incline_press','dumbbell'),('db_incline_press','bench'),
  ('chest_press_machine','machine'),
  ('cable_chest_press','cable'),
  ('cable_fly','cable'),
  ('pec_deck','machine'),
  ('pushup','bodyweight'),
  ('chest_dip','dip_bars'),('chest_dip','bodyweight'),
  ('chinup','pullup_bar'),('chinup','bodyweight'),
  ('lat_pulldown_neutral','cable'),('lat_pulldown_neutral','machine'),
  ('lat_pulldown_single','cable'),
  ('barbell_row','barbell'),
  ('db_row','dumbbell'),('db_row','bench'),
  ('cable_row','cable'),
  ('chest_supported_row','machine'),
  ('row_machine','machine'),
  ('straight_arm_pulldown','cable'),
  ('face_pull','cable'),
  ('db_shoulder_press','dumbbell'),
  ('shoulder_press_machine','machine'),
  ('cable_lateral_raise','cable'),
  ('machine_lateral_raise','machine'),
  ('reverse_fly','dumbbell'),
  ('reverse_pec_deck','machine'),
  ('rear_delt_cable','cable'),
  ('front_squat','barbell'),('front_squat','rack'),
  ('hack_squat','machine'),
  ('step_up','dumbbell'),('step_up','bench'),
  ('walking_lunge','dumbbell'),
  ('reverse_lunge','dumbbell'),
  ('deadlift','barbell'),
  ('glute_bridge','bodyweight'),
  ('seated_leg_curl','machine'),
  ('lying_leg_curl','machine'),
  ('leg_extension','machine'),
  ('adductor_machine','machine'),
  ('abductor_machine','machine'),
  ('standing_calf_raise','machine'),
  ('seated_calf_raise','machine'),
  ('barbell_curl','barbell'),
  ('db_curl','dumbbell'),
  ('hammer_curl','dumbbell'),
  ('incline_curl','dumbbell'),('incline_curl','bench'),
  ('cable_curl','cable'),
  ('preacher_curl','machine'),
  ('rope_pushdown','cable'),
  ('overhead_triceps','cable'),
  ('skull_crusher','barbell'),('skull_crusher','bench'),
  ('close_grip_bench','barbell'),('close_grip_bench','bench'),
  ('triceps_dip','dip_bars'),('triceps_dip','bodyweight'),
  ('cable_crunch','cable'),
  ('crunch','bodyweight'),
  ('hanging_leg_raise','pullup_bar'),('hanging_leg_raise','bodyweight'),
  ('lying_leg_raise','bodyweight'),
  ('ab_wheel','bodyweight'),
  ('side_plank','bodyweight'),
  ('pallof_press','cable'),
  ('back_extension','machine'),
  ('farmer_carry','dumbbell')
 ) as v(slug,ek) on e.slug = v.slug
on conflict (exercise_id, equipment_key) do nothing;

insert into public.schema_migrations(version) values ('0006_exercise_library_expansion') on conflict (version) do nothing;
