-- ============================================================
--  ORVIA · 0047 — Übungskatalog als Basisbewegung × Variante (S2b-1, 14.09.2026)
--  Generiert aus app/tools/catalog-gen.mjs. Idempotent, löscht nichts.
--  · exercises.base_slug + exercises.variant {equipment, grip, angle, execution}
--  · 224 Systemübungen (46 Basisbewegungen); bestehende Slugs behalten Name,
--    bekommen base_slug/variant/Aliasse (nur wenn leer) und fehlende Muskel-/Gerätezuordnungen
--  · Muskelzuordnung ist die Wahrheit für gym-volume/Kraftprofil (Client liest sie ab v8-380 mit)
-- ============================================================
alter table public.exercises add column if not exists base_slug text;
alter table public.exercises add column if not exists variant jsonb not null default '{}'::jsonb;
create index if not exists exercises_base_idx on public.exercises (base_slug);
insert into public.movement_patterns (key, name) values ('shoulder_flexion','Schulterflexion'),('shoulder_elevation','Schulterhebung'),('wrist_flexion','Handgelenk') on conflict (key) do nothing;
insert into public.equipment (key, name) values ('ez_bar','SZ-Stange'),('trap_bar','Trap Bar'),('t_bar','T-Bar'),('plate','Hantelscheibe'),('box','Box / Erhöhung') on conflict (key) do nothing;

insert into public.exercises (slug, is_system, name, aliases, category, movement_pattern, difficulty, unilateral, bodyweight, base_slug, variant) values
 ('bench_press',true,'Bankdrücken',array['barbell bench press','flachbank']::text[],'compound','horizontal_push','beginner',false,false,'bench_press','{"equipment":"barbell","angle":"flat"}'::jsonb),
 ('db_bench_press',true,'Kurzhantel-Bankdrücken',array['dumbbell bench press']::text[],'compound','horizontal_push','beginner',false,false,'bench_press','{"equipment":"dumbbell","angle":"flat"}'::jsonb),
 ('smith_bench_press',true,'Bankdrücken Smith Machine',array['smith bench']::text[],'compound','horizontal_push','beginner',false,false,'bench_press','{"equipment":"smith","angle":"flat"}'::jsonb),
 ('close_grip_bench',true,'Enges Bankdrücken',array['close grip bench']::text[],'compound','horizontal_push','intermediate',false,false,'bench_press','{"equipment":"barbell","grip":"close","angle":"flat"}'::jsonb),
 ('floor_press',true,'Floor Press',array[]::text[],'compound','horizontal_push','intermediate',false,false,'bench_press','{"equipment":"barbell","angle":"flat","execution":"floor"}'::jsonb),
 ('incline_bench_press',true,'Schrägbankdrücken',array['incline bench press']::text[],'compound','horizontal_push','beginner',false,false,'incline_press','{"equipment":"barbell","angle":"incline"}'::jsonb),
 ('db_incline_press',true,'Kurzhantel-Schrägbankdrücken',array['incline dumbbell press']::text[],'compound','horizontal_push','beginner',false,false,'incline_press','{"equipment":"dumbbell","angle":"incline"}'::jsonb),
 ('smith_incline_press',true,'Schrägbankdrücken Smith Machine',array[]::text[],'compound','horizontal_push','beginner',false,false,'incline_press','{"equipment":"smith","angle":"incline"}'::jsonb),
 ('incline_press_machine',true,'Schrägbankpresse Maschine',array['incline press machine']::text[],'compound','horizontal_push','beginner',false,false,'incline_press','{"equipment":"machine","angle":"incline"}'::jsonb),
 ('decline_bench_press',true,'Negativbankdrücken',array['decline bench press']::text[],'compound','horizontal_push','intermediate',false,false,'decline_press','{"equipment":"barbell","angle":"decline"}'::jsonb),
 ('db_decline_press',true,'Kurzhantel-Negativbankdrücken',array[]::text[],'compound','horizontal_push','intermediate',false,false,'decline_press','{"equipment":"dumbbell","angle":"decline"}'::jsonb),
 ('chest_press_machine',true,'Brustpresse Maschine',array['chest press machine']::text[],'compound','horizontal_push','beginner',false,false,'chest_press','{"equipment":"machine","angle":"flat"}'::jsonb),
 ('chest_press_machine_incline',true,'Brustpresse Maschine schräg',array[]::text[],'compound','horizontal_push','beginner',false,false,'chest_press','{"equipment":"machine","angle":"incline"}'::jsonb),
 ('cable_chest_press',true,'Brustpresse Kabel',array['cable press']::text[],'compound','horizontal_push','beginner',false,false,'chest_press','{"equipment":"cable","angle":"flat"}'::jsonb),
 ('cable_chest_press_single',true,'Brustpresse Kabel einarmig',array[]::text[],'compound','horizontal_push','intermediate',true,false,'chest_press','{"equipment":"cable","execution":"single_arm"}'::jsonb),
 ('pec_deck',true,'Butterfly / Pec Deck',array['butterfly','pec deck','fly machine']::text[],'isolation','horizontal_push','beginner',false,false,'chest_fly','{"equipment":"machine"}'::jsonb),
 ('cable_fly',true,'Kabel-Flys',array['cable fly','cable crossover']::text[],'isolation','horizontal_push','beginner',false,false,'chest_fly','{"equipment":"cable","angle":"mid"}'::jsonb),
 ('cable_fly_high',true,'Kabel-Flys von oben',array['high to low fly','cable crossover high']::text[],'isolation','horizontal_push','beginner',false,false,'chest_fly','{"equipment":"cable","angle":"high_to_low"}'::jsonb),
 ('cable_fly_low',true,'Kabel-Flys von unten',array['low to high fly']::text[],'isolation','horizontal_push','beginner',false,false,'chest_fly','{"equipment":"cable","angle":"low_to_high"}'::jsonb),
 ('db_fly',true,'Kurzhantel-Flys',array['dumbbell fly','fliegende']::text[],'isolation','horizontal_push','beginner',false,false,'chest_fly','{"equipment":"dumbbell","angle":"flat"}'::jsonb),
 ('db_incline_fly',true,'Kurzhantel-Flys Schrägbank',array['incline dumbbell fly']::text[],'isolation','horizontal_push','beginner',false,false,'chest_fly','{"equipment":"dumbbell","angle":"incline"}'::jsonb),
 ('pushup',true,'Liegestütze',array['push-up','push up']::text[],'compound','horizontal_push','beginner',false,true,'pushup','{"equipment":"bodyweight"}'::jsonb),
 ('pushup_incline',true,'Liegestütze erhöht',array['incline pushup']::text[],'compound','horizontal_push','beginner',false,true,'pushup','{"equipment":"bodyweight","angle":"incline"}'::jsonb),
 ('pushup_decline',true,'Liegestütze Füße erhöht',array['decline pushup']::text[],'compound','horizontal_push','intermediate',false,true,'pushup','{"equipment":"bodyweight","angle":"decline"}'::jsonb),
 ('pushup_weighted',true,'Liegestütze mit Zusatzlast',array['weighted pushup']::text[],'compound','horizontal_push','intermediate',false,true,'pushup','{"equipment":"bodyweight","execution":"weighted"}'::jsonb),
 ('chest_dip',true,'Dips (brustbetont)',array['chest dips']::text[],'compound','horizontal_push','intermediate',false,true,'dip','{"equipment":"bodyweight","execution":"lean_forward"}'::jsonb),
 ('triceps_dip',true,'Dips (trizepsbetont)',array['triceps dips']::text[],'compound','horizontal_push','intermediate',false,true,'dip','{"equipment":"bodyweight","execution":"upright"}'::jsonb),
 ('dip_machine',true,'Dip-Maschine',array['assisted dip','seated dip machine']::text[],'compound','horizontal_push','beginner',false,false,'dip','{"equipment":"machine"}'::jsonb),
 ('bench_dip',true,'Bank-Dips',array['bench dips']::text[],'compound','horizontal_push','beginner',false,true,'dip','{"equipment":"bodyweight","execution":"bench"}'::jsonb),
 ('overhead_press',true,'Schulterdrücken Langhantel',array['overhead press','ohp','military press']::text[],'compound','vertical_push','intermediate',false,false,'overhead_press','{"equipment":"barbell","execution":"standing"}'::jsonb),
 ('seated_barbell_press',true,'Schulterdrücken Langhantel sitzend',array['seated ohp']::text[],'compound','vertical_push','intermediate',false,false,'overhead_press','{"equipment":"barbell","execution":"seated"}'::jsonb),
 ('db_shoulder_press',true,'Schulterdrücken Kurzhantel',array['dumbbell shoulder press']::text[],'compound','vertical_push','beginner',false,false,'overhead_press','{"equipment":"dumbbell","execution":"seated"}'::jsonb),
 ('arnold_press',true,'Arnold Press',array[]::text[],'compound','vertical_push','intermediate',false,false,'overhead_press','{"equipment":"dumbbell","execution":"rotating"}'::jsonb),
 ('smith_shoulder_press',true,'Schulterdrücken Smith Machine',array[]::text[],'compound','vertical_push','beginner',false,false,'overhead_press','{"equipment":"smith","execution":"seated"}'::jsonb),
 ('shoulder_press_machine',true,'Schulterpresse Maschine',array['shoulder press machine']::text[],'compound','vertical_push','beginner',false,false,'overhead_press','{"equipment":"machine"}'::jsonb),
 ('landmine_press',true,'Landmine Press',array[]::text[],'compound','vertical_push','intermediate',true,false,'overhead_press','{"equipment":"barbell","execution":"landmine"}'::jsonb),
 ('push_press',true,'Push Press',array[]::text[],'compound','vertical_push','advanced',false,false,'overhead_press','{"equipment":"barbell","execution":"push"}'::jsonb),
 ('lateral_raise',true,'Seitheben Kurzhantel',array['lateral raise','side raise']::text[],'isolation','shoulder_abduction','beginner',false,false,'lateral_raise','{"equipment":"dumbbell"}'::jsonb),
 ('cable_lateral_raise',true,'Seitheben Kabel',array['cable lateral raise']::text[],'isolation','shoulder_abduction','beginner',true,false,'lateral_raise','{"equipment":"cable","execution":"single_arm"}'::jsonb),
 ('machine_lateral_raise',true,'Seitheben Maschine',array['lateral raise machine']::text[],'isolation','shoulder_abduction','beginner',false,false,'lateral_raise','{"equipment":"machine"}'::jsonb),
 ('lean_away_lateral_raise',true,'Seitheben angelehnt',array['leaning lateral raise']::text[],'isolation','shoulder_abduction','intermediate',true,false,'lateral_raise','{"equipment":"dumbbell","execution":"leaning"}'::jsonb),
 ('front_raise',true,'Frontheben Kurzhantel',array['front raise']::text[],'isolation','shoulder_flexion','beginner',false,false,'front_raise','{"equipment":"dumbbell"}'::jsonb),
 ('cable_front_raise',true,'Frontheben Kabel',array[]::text[],'isolation','shoulder_flexion','beginner',false,false,'front_raise','{"equipment":"cable"}'::jsonb),
 ('plate_front_raise',true,'Frontheben Scheibe',array[]::text[],'isolation','shoulder_flexion','beginner',false,false,'front_raise','{"equipment":"plate"}'::jsonb),
 ('reverse_fly',true,'Reverse Flys Kurzhantel',array['rear delt fly','bent over fly']::text[],'isolation','horizontal_pull','beginner',false,false,'rear_delt','{"equipment":"dumbbell"}'::jsonb),
 ('reverse_pec_deck',true,'Reverse Pec Deck',array['reverse butterfly','rear delt machine']::text[],'isolation','horizontal_pull','beginner',false,false,'rear_delt','{"equipment":"machine"}'::jsonb),
 ('rear_delt_cable',true,'Rear-Delt Kabelzug',array['cable rear delt fly']::text[],'isolation','horizontal_pull','beginner',false,false,'rear_delt','{"equipment":"cable"}'::jsonb),
 ('chest_supported_reverse_fly',true,'Reverse Flys brustgestützt',array[]::text[],'isolation','horizontal_pull','beginner',false,false,'rear_delt','{"equipment":"dumbbell","execution":"chest_supported"}'::jsonb),
 ('face_pull',true,'Face Pulls',array['face pull']::text[],'isolation','horizontal_pull','beginner',false,false,'face_pull','{"equipment":"cable","grip":"rope"}'::jsonb),
 ('band_face_pull',true,'Face Pulls Band',array[]::text[],'isolation','horizontal_pull','beginner',false,false,'face_pull','{"equipment":"band"}'::jsonb),
 ('upright_row',true,'Aufrechtes Rudern Langhantel',array['upright row']::text[],'compound','shoulder_abduction','intermediate',false,false,'upright_row','{"equipment":"barbell","grip":"wide"}'::jsonb),
 ('cable_upright_row',true,'Aufrechtes Rudern Kabel',array[]::text[],'compound','shoulder_abduction','beginner',false,false,'upright_row','{"equipment":"cable","grip":"rope"}'::jsonb),
 ('barbell_shrug',true,'Shrugs Langhantel',array['shrugs']::text[],'isolation','shoulder_elevation','beginner',false,false,'shrug','{"equipment":"barbell"}'::jsonb),
 ('db_shrug',true,'Shrugs Kurzhantel',array[]::text[],'isolation','shoulder_elevation','beginner',false,false,'shrug','{"equipment":"dumbbell"}'::jsonb),
 ('smith_shrug',true,'Shrugs Smith Machine',array[]::text[],'isolation','shoulder_elevation','beginner',false,false,'shrug','{"equipment":"smith"}'::jsonb),
 ('trap_bar_shrug',true,'Shrugs Trap Bar',array[]::text[],'isolation','shoulder_elevation','beginner',false,false,'shrug','{"equipment":"trap_bar"}'::jsonb),
 ('pullup',true,'Klimmzüge',array['pull-up','pull up','klimmzug']::text[],'compound','vertical_pull','intermediate',false,true,'pullup','{"equipment":"bodyweight","grip":"overhand_medium"}'::jsonb),
 ('pullup_wide',true,'Klimmzüge breit',array['wide grip pull-up','breiter klimmzug']::text[],'compound','vertical_pull','intermediate',false,true,'pullup','{"equipment":"bodyweight","grip":"overhand_wide"}'::jsonb),
 ('pullup_neutral',true,'Klimmzüge neutral',array['neutral grip pull-up','hammer grip pullup']::text[],'compound','vertical_pull','intermediate',false,true,'pullup','{"equipment":"bodyweight","grip":"neutral"}'::jsonb),
 ('chinup',true,'Chin-ups',array['chin up','klimmzüge untergriff']::text[],'compound','vertical_pull','intermediate',false,true,'pullup','{"equipment":"bodyweight","grip":"underhand"}'::jsonb),
 ('pullup_weighted',true,'Klimmzüge mit Zusatzlast',array['weighted pull-up']::text[],'compound','vertical_pull','advanced',false,true,'pullup','{"equipment":"bodyweight","execution":"weighted"}'::jsonb),
 ('pullup_assisted',true,'Klimmzüge assistiert',array['assisted pull-up','klimmzugmaschine']::text[],'compound','vertical_pull','beginner',false,false,'pullup','{"equipment":"machine","execution":"assisted"}'::jsonb),
 ('pullup_band',true,'Klimmzüge mit Band',array['band assisted pull-up']::text[],'compound','vertical_pull','beginner',false,true,'pullup','{"equipment":"band","execution":"assisted"}'::jsonb),
 ('lat_pulldown',true,'Latzug breit',array['lat pulldown','latziehen']::text[],'compound','vertical_pull','beginner',false,false,'lat_pulldown','{"equipment":"cable","grip":"overhand_wide"}'::jsonb),
 ('lat_pulldown_close',true,'Latzug eng',array['close grip pulldown']::text[],'compound','vertical_pull','beginner',false,false,'lat_pulldown','{"equipment":"cable","grip":"overhand_close"}'::jsonb),
 ('lat_pulldown_neutral',true,'Latzug neutral (V-Griff)',array['neutral grip pulldown','v-bar pulldown']::text[],'compound','vertical_pull','beginner',false,false,'lat_pulldown','{"equipment":"cable","grip":"neutral"}'::jsonb),
 ('lat_pulldown_underhand',true,'Latzug Untergriff',array['underhand pulldown','reverse grip pulldown']::text[],'compound','vertical_pull','beginner',false,false,'lat_pulldown','{"equipment":"cable","grip":"underhand"}'::jsonb),
 ('lat_pulldown_single',true,'Latzug einarmig',array['single arm pulldown']::text[],'compound','vertical_pull','intermediate',true,false,'lat_pulldown','{"equipment":"cable","execution":"single_arm"}'::jsonb),
 ('lat_pulldown_machine',true,'Latzug Maschine',array['lat pulldown machine','plate loaded pulldown']::text[],'compound','vertical_pull','beginner',false,false,'lat_pulldown','{"equipment":"machine"}'::jsonb),
 ('straight_arm_pulldown',true,'Straight-Arm Pulldown',array['straight arm pulldown','lat pushdown']::text[],'isolation','vertical_pull','beginner',false,false,'pullover','{"equipment":"cable","grip":"bar"}'::jsonb),
 ('rope_pullover',true,'Kabel-Überzüge Seil',array['rope pullover']::text[],'isolation','vertical_pull','beginner',false,false,'pullover','{"equipment":"cable","grip":"rope"}'::jsonb),
 ('db_pullover',true,'Kurzhantel-Überzüge',array['dumbbell pullover']::text[],'isolation','vertical_pull','intermediate',false,false,'pullover','{"equipment":"dumbbell"}'::jsonb),
 ('pullover_machine',true,'Pullover Maschine',array[]::text[],'isolation','vertical_pull','beginner',false,false,'pullover','{"equipment":"machine"}'::jsonb),
 ('row',true,'Rudern (allgemein)',array['rudern']::text[],'compound','horizontal_pull','beginner',false,false,'row','{"equipment":"barbell"}'::jsonb),
 ('barbell_row',true,'Langhantelrudern',array['barbell row','bent over row']::text[],'compound','horizontal_pull','intermediate',false,false,'row','{"equipment":"barbell","grip":"overhand"}'::jsonb),
 ('barbell_row_underhand',true,'Langhantelrudern Untergriff',array['yates row','underhand row']::text[],'compound','horizontal_pull','intermediate',false,false,'row','{"equipment":"barbell","grip":"underhand"}'::jsonb),
 ('pendlay_row',true,'Pendlay Row',array[]::text[],'compound','horizontal_pull','advanced',false,false,'row','{"equipment":"barbell","execution":"from_floor"}'::jsonb),
 ('db_row',true,'Kurzhantelrudern einarmig',array['dumbbell row','one arm row']::text[],'compound','horizontal_pull','beginner',true,false,'row','{"equipment":"dumbbell","execution":"single_arm"}'::jsonb),
 ('db_row_both',true,'Kurzhantelrudern beidseitig',array[]::text[],'compound','horizontal_pull','beginner',false,false,'row','{"equipment":"dumbbell","execution":"bilateral"}'::jsonb),
 ('chest_supported_row',true,'Brustgestütztes Rudern Kurzhantel',array['chest supported row','incline row']::text[],'compound','horizontal_pull','beginner',false,false,'row','{"equipment":"dumbbell","execution":"chest_supported"}'::jsonb),
 ('seal_row',true,'Seal Row',array[]::text[],'compound','horizontal_pull','intermediate',false,false,'row','{"equipment":"barbell","execution":"chest_supported"}'::jsonb),
 ('t_bar_row',true,'T-Bar Rudern',array['t-bar row','t bar row']::text[],'compound','horizontal_pull','intermediate',false,false,'row','{"equipment":"t_bar","grip":"neutral"}'::jsonb),
 ('t_bar_row_supported',true,'T-Bar Rudern brustgestützt',array['chest supported t-bar row']::text[],'compound','horizontal_pull','beginner',false,false,'row','{"equipment":"t_bar","execution":"chest_supported"}'::jsonb),
 ('cable_row',true,'Kabelrudern V-Griff',array['seated cable row','kabelrudern']::text[],'compound','horizontal_pull','beginner',false,false,'row','{"equipment":"cable","grip":"neutral_close"}'::jsonb),
 ('cable_row_wide',true,'Kabelrudern breit',array['wide grip cable row']::text[],'compound','horizontal_pull','beginner',false,false,'row','{"equipment":"cable","grip":"overhand_wide"}'::jsonb),
 ('cable_row_rope',true,'Kabelrudern Seil',array[]::text[],'compound','horizontal_pull','beginner',false,false,'row','{"equipment":"cable","grip":"rope"}'::jsonb),
 ('cable_row_single',true,'Kabelrudern einarmig',array['single arm cable row']::text[],'compound','horizontal_pull','intermediate',true,false,'row','{"equipment":"cable","execution":"single_arm"}'::jsonb),
 ('row_machine',true,'Rudermaschine',array['row machine','seated row machine']::text[],'compound','horizontal_pull','beginner',false,false,'row','{"equipment":"machine"}'::jsonb),
 ('row_machine_high',true,'Rudermaschine hoch (High Row)',array['high row']::text[],'compound','horizontal_pull','beginner',false,false,'row','{"equipment":"machine","angle":"high"}'::jsonb),
 ('smith_row',true,'Rudern Smith Machine',array[]::text[],'compound','horizontal_pull','beginner',false,false,'row','{"equipment":"smith"}'::jsonb),
 ('inverted_row',true,'Inverted Rows',array['australian pull-up','body row']::text[],'compound','horizontal_pull','beginner',false,true,'row','{"equipment":"bodyweight"}'::jsonb),
 ('meadows_row',true,'Meadows Row',array[]::text[],'compound','horizontal_pull','advanced',true,false,'row','{"equipment":"barbell","execution":"landmine"}'::jsonb),
 ('squat',true,'Kniebeuge Langhantel',array['back squat','squat','kniebeugen']::text[],'compound','squat','intermediate',false,false,'squat','{"equipment":"barbell","execution":"high_bar"}'::jsonb),
 ('low_bar_squat',true,'Kniebeuge Low Bar',array['low bar squat']::text[],'compound','squat','intermediate',false,false,'squat','{"equipment":"barbell","execution":"low_bar"}'::jsonb),
 ('front_squat',true,'Frontkniebeuge',array['front squat']::text[],'compound','squat','advanced',false,false,'squat','{"equipment":"barbell","execution":"front"}'::jsonb),
 ('smith_squat',true,'Kniebeuge Smith Machine',array['smith squat']::text[],'compound','squat','beginner',false,false,'squat','{"equipment":"smith"}'::jsonb),
 ('goblet_squat',true,'Goblet Squat',array['goblet']::text[],'compound','squat','beginner',false,false,'squat','{"equipment":"dumbbell","execution":"goblet"}'::jsonb),
 ('sumo_squat',true,'Sumo Squat',array['sumo kniebeuge']::text[],'compound','squat','beginner',false,false,'squat','{"equipment":"dumbbell","execution":"sumo"}'::jsonb),
 ('zercher_squat',true,'Zercher Squat',array[]::text[],'compound','squat','advanced',false,false,'squat','{"equipment":"barbell","execution":"zercher"}'::jsonb),
 ('safety_bar_squat',true,'Safety-Bar Squat',array['ssb squat']::text[],'compound','squat','intermediate',false,false,'squat','{"equipment":"barbell","execution":"safety_bar"}'::jsonb),
 ('box_squat',true,'Box Squat',array[]::text[],'compound','squat','intermediate',false,false,'squat','{"equipment":"barbell","execution":"box"}'::jsonb),
 ('belt_squat',true,'Belt Squat',array[]::text[],'compound','squat','intermediate',false,false,'squat','{"equipment":"machine","execution":"belt"}'::jsonb),
 ('pendulum_squat',true,'Pendulum Squat',array[]::text[],'compound','squat','beginner',false,false,'squat','{"equipment":"machine","execution":"pendulum"}'::jsonb),
 ('bodyweight_squat',true,'Kniebeuge Körpergewicht',array['air squat']::text[],'compound','squat','beginner',false,true,'squat','{"equipment":"bodyweight"}'::jsonb),
 ('leg_press',true,'Beinpresse 45°',array['leg press','beinpresse']::text[],'compound','squat','beginner',false,false,'leg_press','{"equipment":"leg_press","angle":"45"}'::jsonb),
 ('leg_press_horizontal',true,'Beinpresse horizontal',array['seated leg press']::text[],'compound','squat','beginner',false,false,'leg_press','{"equipment":"machine","angle":"horizontal"}'::jsonb),
 ('leg_press_single',true,'Beinpresse einbeinig',array['single leg press']::text[],'compound','squat','intermediate',true,false,'leg_press','{"equipment":"leg_press","execution":"single_leg"}'::jsonb),
 ('leg_press_high_feet',true,'Beinpresse Füße hoch',array[]::text[],'compound','squat','beginner',false,false,'leg_press','{"equipment":"leg_press","execution":"feet_high"}'::jsonb),
 ('hack_squat',true,'Hackenschmidt-Kniebeuge',array['hack squat']::text[],'compound','squat','beginner',false,false,'hack_squat','{"equipment":"machine"}'::jsonb),
 ('reverse_hack_squat',true,'Reverse Hack Squat',array[]::text[],'compound','squat','intermediate',false,false,'hack_squat','{"equipment":"machine","execution":"reverse"}'::jsonb),
 ('v_squat',true,'V-Squat Maschine',array['v squat']::text[],'compound','squat','beginner',false,false,'hack_squat','{"equipment":"machine","execution":"v_squat"}'::jsonb),
 ('sissy_squat',true,'Sissy Squat',array[]::text[],'compound','squat','advanced',false,true,'hack_squat','{"equipment":"bodyweight"}'::jsonb),
 ('walking_lunge',true,'Ausfallschritte gehend',array['walking lunge']::text[],'compound','lunge','beginner',true,false,'lunge','{"equipment":"dumbbell","execution":"walking"}'::jsonb),
 ('reverse_lunge',true,'Ausfallschritte rückwärts',array['reverse lunge']::text[],'compound','lunge','beginner',true,false,'lunge','{"equipment":"dumbbell","execution":"reverse"}'::jsonb),
 ('forward_lunge',true,'Ausfallschritte vorwärts',array['forward lunge','ausfallschritt']::text[],'compound','lunge','beginner',true,false,'lunge','{"equipment":"dumbbell","execution":"forward"}'::jsonb),
 ('barbell_lunge',true,'Ausfallschritte Langhantel',array['barbell lunge']::text[],'compound','lunge','intermediate',true,false,'lunge','{"equipment":"barbell"}'::jsonb),
 ('smith_lunge',true,'Ausfallschritte Smith Machine',array[]::text[],'compound','lunge','beginner',true,false,'lunge','{"equipment":"smith"}'::jsonb),
 ('lateral_lunge',true,'Seitliche Ausfallschritte',array['lateral lunge','side lunge']::text[],'compound','lunge','beginner',true,false,'lunge','{"equipment":"dumbbell","execution":"lateral"}'::jsonb),
 ('bulgarian_split_squat',true,'Bulgarian Split Squat',array['bulgarian','rear foot elevated split squat']::text[],'compound','lunge','intermediate',true,false,'split_squat','{"equipment":"dumbbell","execution":"rear_foot_elevated"}'::jsonb),
 ('smith_split_squat',true,'Split Squat Smith Machine',array[]::text[],'compound','lunge','beginner',true,false,'split_squat','{"equipment":"smith"}'::jsonb),
 ('split_squat',true,'Split Squat',array[]::text[],'compound','lunge','beginner',true,false,'split_squat','{"equipment":"dumbbell"}'::jsonb),
 ('step_up',true,'Step-ups',array['step up']::text[],'compound','lunge','beginner',true,false,'step_up','{"equipment":"dumbbell"}'::jsonb),
 ('step_up_barbell',true,'Step-ups Langhantel',array[]::text[],'compound','lunge','intermediate',true,false,'step_up','{"equipment":"barbell"}'::jsonb),
 ('deadlift',true,'Kreuzheben konventionell',array['deadlift','kreuzheben']::text[],'compound','hinge','intermediate',false,false,'deadlift','{"equipment":"barbell","execution":"conventional"}'::jsonb),
 ('sumo_deadlift',true,'Kreuzheben Sumo',array['sumo deadlift']::text[],'compound','hinge','intermediate',false,false,'deadlift','{"equipment":"barbell","execution":"sumo"}'::jsonb),
 ('trap_bar_deadlift',true,'Kreuzheben Trap Bar',array['trap bar deadlift','hex bar deadlift']::text[],'compound','hinge','beginner',false,false,'deadlift','{"equipment":"trap_bar"}'::jsonb),
 ('deficit_deadlift',true,'Kreuzheben Defizit',array[]::text[],'compound','hinge','advanced',false,false,'deadlift','{"equipment":"barbell","execution":"deficit"}'::jsonb),
 ('rack_pull',true,'Rack Pulls',array['rack pull']::text[],'compound','hinge','intermediate',false,false,'deadlift','{"equipment":"barbell","execution":"partial"}'::jsonb),
 ('romanian_deadlift',true,'Rumänisches Kreuzheben',array['rdl','romanian deadlift']::text[],'compound','hinge','intermediate',false,false,'rdl','{"equipment":"barbell"}'::jsonb),
 ('db_rdl',true,'Rumänisches Kreuzheben Kurzhantel',array['dumbbell rdl']::text[],'compound','hinge','beginner',false,false,'rdl','{"equipment":"dumbbell"}'::jsonb),
 ('single_leg_rdl',true,'Einbeiniges RDL',array['single leg rdl','single leg deadlift']::text[],'compound','hinge','intermediate',true,false,'rdl','{"equipment":"dumbbell","execution":"single_leg"}'::jsonb),
 ('stiff_leg_deadlift',true,'Gestrecktes Kreuzheben',array['stiff leg deadlift','sldl']::text[],'compound','hinge','intermediate',false,false,'rdl','{"equipment":"barbell","execution":"stiff_leg"}'::jsonb),
 ('smith_rdl',true,'RDL Smith Machine',array[]::text[],'compound','hinge','beginner',false,false,'rdl','{"equipment":"smith"}'::jsonb),
 ('good_morning',true,'Good Mornings',array['good morning']::text[],'compound','hinge','advanced',false,false,'good_morning','{"equipment":"barbell"}'::jsonb),
 ('hip_thrust',true,'Hip Thrust Langhantel',array['hip thrust','barbell hip thrust']::text[],'compound','hip_extension','beginner',false,false,'hip_thrust','{"equipment":"barbell"}'::jsonb),
 ('hip_thrust_machine',true,'Hip Thrust Maschine',array['glute drive']::text[],'compound','hip_extension','beginner',false,false,'hip_thrust','{"equipment":"machine"}'::jsonb),
 ('smith_hip_thrust',true,'Hip Thrust Smith Machine',array[]::text[],'compound','hip_extension','beginner',false,false,'hip_thrust','{"equipment":"smith"}'::jsonb),
 ('single_leg_hip_thrust',true,'Hip Thrust einbeinig',array[]::text[],'compound','hip_extension','beginner',true,true,'hip_thrust','{"equipment":"bodyweight","execution":"single_leg"}'::jsonb),
 ('glute_bridge',true,'Glute Bridge',array['bridge']::text[],'compound','hip_extension','beginner',false,true,'hip_thrust','{"equipment":"bodyweight","execution":"floor"}'::jsonb),
 ('cable_pull_through',true,'Cable Pull-Through',array['pull through']::text[],'compound','hip_extension','beginner',false,false,'hip_thrust','{"equipment":"cable","grip":"rope"}'::jsonb),
 ('kettlebell_swing',true,'Kettlebell Swing',array['kb swing']::text[],'compound','hip_extension','intermediate',false,false,'hip_thrust','{"equipment":"kettlebell"}'::jsonb),
 ('back_extension',true,'Rückenstrecker 45°',array['hyperextension','back extension']::text[],'compound','trunk_extension','beginner',false,true,'back_extension','{"equipment":"bodyweight","angle":"45"}'::jsonb),
 ('back_extension_machine',true,'Rückenstrecker Maschine',array[]::text[],'compound','trunk_extension','beginner',false,false,'back_extension','{"equipment":"machine"}'::jsonb),
 ('reverse_hyper',true,'Reverse Hyperextension',array['reverse hyper']::text[],'compound','trunk_extension','intermediate',false,false,'back_extension','{"equipment":"machine","execution":"reverse"}'::jsonb),
 ('seated_leg_curl',true,'Beinbeuger sitzend',array['seated leg curl']::text[],'isolation','knee_flexion','beginner',false,false,'leg_curl','{"equipment":"machine","execution":"seated"}'::jsonb),
 ('lying_leg_curl',true,'Beinbeuger liegend',array['lying leg curl']::text[],'isolation','knee_flexion','beginner',false,false,'leg_curl','{"equipment":"machine","execution":"lying"}'::jsonb),
 ('leg_curl',true,'Beinbeuger',array['leg curl']::text[],'isolation','knee_flexion','beginner',false,false,'leg_curl','{"equipment":"machine"}'::jsonb),
 ('standing_leg_curl',true,'Beinbeuger stehend einbeinig',array['standing leg curl']::text[],'isolation','knee_flexion','beginner',true,false,'leg_curl','{"equipment":"machine","execution":"standing"}'::jsonb),
 ('nordic_curl',true,'Nordic Hamstring Curls',array['nordics','nordic curl']::text[],'isolation','knee_flexion','advanced',false,true,'leg_curl','{"equipment":"bodyweight"}'::jsonb),
 ('slider_leg_curl',true,'Beinbeuger Slider / Ball',array['slider curl','swiss ball curl']::text[],'isolation','knee_flexion','intermediate',false,true,'leg_curl','{"equipment":"bodyweight"}'::jsonb),
 ('leg_extension',true,'Beinstrecker',array['leg extension']::text[],'isolation','knee_extension','beginner',false,false,'leg_extension','{"equipment":"machine"}'::jsonb),
 ('leg_extension_single',true,'Beinstrecker einbeinig',array[]::text[],'isolation','knee_extension','beginner',true,false,'leg_extension','{"equipment":"machine","execution":"single_leg"}'::jsonb),
 ('standing_calf_raise',true,'Wadenheben stehend',array['standing calf raise']::text[],'isolation','calf','beginner',false,false,'calf_raise','{"equipment":"machine","execution":"standing"}'::jsonb),
 ('seated_calf_raise',true,'Wadenheben sitzend',array['seated calf raise']::text[],'isolation','calf','beginner',false,false,'calf_raise','{"equipment":"machine","execution":"seated"}'::jsonb),
 ('calf_raise',true,'Wadenheben',array['calf raise']::text[],'isolation','calf','beginner',false,true,'calf_raise','{"equipment":"bodyweight"}'::jsonb),
 ('leg_press_calf_raise',true,'Wadenheben Beinpresse',array['calf press']::text[],'isolation','calf','beginner',false,false,'calf_raise','{"equipment":"leg_press"}'::jsonb),
 ('smith_calf_raise',true,'Wadenheben Smith Machine',array[]::text[],'isolation','calf','beginner',false,false,'calf_raise','{"equipment":"smith"}'::jsonb),
 ('single_leg_calf_raise',true,'Wadenheben einbeinig',array[]::text[],'isolation','calf','beginner',true,false,'calf_raise','{"equipment":"dumbbell","execution":"single_leg"}'::jsonb),
 ('adductor_machine',true,'Adduktorenmaschine',array['adductor machine','hip adduction']::text[],'isolation','hip_adduction','beginner',false,false,'hip_adduction','{"equipment":"machine"}'::jsonb),
 ('cable_adduction',true,'Adduktion Kabel',array[]::text[],'isolation','hip_adduction','beginner',true,false,'hip_adduction','{"equipment":"cable"}'::jsonb),
 ('copenhagen_plank',true,'Copenhagen Plank',array['copenhagen']::text[],'isolation','hip_adduction','intermediate',true,true,'hip_adduction','{"equipment":"bodyweight"}'::jsonb),
 ('abductor_machine',true,'Abduktorenmaschine',array['abductor machine','hip abduction']::text[],'isolation','hip_abduction','beginner',false,false,'hip_abduction','{"equipment":"machine"}'::jsonb),
 ('cable_abduction',true,'Abduktion Kabel',array[]::text[],'isolation','hip_abduction','beginner',true,false,'hip_abduction','{"equipment":"cable"}'::jsonb),
 ('band_abduction',true,'Abduktion Band (Clamshell / Monster Walk)',array['clamshell','monster walk']::text[],'isolation','hip_abduction','beginner',false,false,'hip_abduction','{"equipment":"band"}'::jsonb),
 ('cable_kickback',true,'Kickbacks Kabel',array['cable kickback','glute kickback']::text[],'isolation','hip_extension','beginner',true,false,'glute_kickback','{"equipment":"cable"}'::jsonb),
 ('glute_kickback_machine',true,'Kickback Maschine',array[]::text[],'isolation','hip_extension','beginner',true,false,'glute_kickback','{"equipment":"machine"}'::jsonb),
 ('biceps_curl',true,'Bizepscurls Kurzhantel',array['dumbbell curl','bizeps curls']::text[],'isolation','elbow_flexion','beginner',false,false,'biceps_curl','{"equipment":"dumbbell"}'::jsonb),
 ('db_curl',true,'Kurzhantelcurls wechselnd',array['alternating dumbbell curl']::text[],'isolation','elbow_flexion','beginner',false,false,'biceps_curl','{"equipment":"dumbbell","execution":"alternating"}'::jsonb),
 ('barbell_curl',true,'Langhantelcurls',array['barbell curl']::text[],'isolation','elbow_flexion','beginner',false,false,'biceps_curl','{"equipment":"barbell"}'::jsonb),
 ('ez_bar_curl',true,'SZ-Curls',array['ez bar curl','sz curls']::text[],'isolation','elbow_flexion','beginner',false,false,'biceps_curl','{"equipment":"ez_bar"}'::jsonb),
 ('incline_curl',true,'Schrägbankcurls',array['incline curl']::text[],'isolation','elbow_flexion','beginner',false,false,'biceps_curl','{"equipment":"dumbbell","angle":"incline"}'::jsonb),
 ('cable_curl',true,'Kabelcurls Stange',array['cable curl']::text[],'isolation','elbow_flexion','beginner',false,false,'biceps_curl','{"equipment":"cable","grip":"bar"}'::jsonb),
 ('cable_curl_rope',true,'Kabelcurls Seil',array[]::text[],'isolation','elbow_flexion','beginner',false,false,'biceps_curl','{"equipment":"cable","grip":"rope"}'::jsonb),
 ('bayesian_curl',true,'Bayesian Curl (Kabel hinter dem Körper)',array['bayesian curl']::text[],'isolation','elbow_flexion','intermediate',true,false,'biceps_curl','{"equipment":"cable","execution":"behind_body"}'::jsonb),
 ('preacher_curl',true,'Preacher Curls',array['preacher curl','scott curls']::text[],'isolation','elbow_flexion','beginner',false,false,'biceps_curl','{"equipment":"ez_bar","execution":"preacher"}'::jsonb),
 ('preacher_curl_machine',true,'Bizepsmaschine',array['biceps machine','machine curl']::text[],'isolation','elbow_flexion','beginner',false,false,'biceps_curl','{"equipment":"machine"}'::jsonb),
 ('spider_curl',true,'Spider Curls',array[]::text[],'isolation','elbow_flexion','intermediate',false,false,'biceps_curl','{"equipment":"dumbbell","execution":"spider"}'::jsonb),
 ('concentration_curl',true,'Konzentrationscurls',array['concentration curl']::text[],'isolation','elbow_flexion','beginner',true,false,'biceps_curl','{"equipment":"dumbbell","execution":"concentration"}'::jsonb),
 ('drag_curl',true,'Drag Curls',array[]::text[],'isolation','elbow_flexion','intermediate',false,false,'biceps_curl','{"equipment":"barbell","execution":"drag"}'::jsonb),
 ('hammer_curl',true,'Hammercurls',array['hammer curl']::text[],'isolation','elbow_flexion','beginner',false,false,'hammer_curl','{"equipment":"dumbbell"}'::jsonb),
 ('cable_hammer_curl',true,'Hammercurls Seil',array['rope hammer curl']::text[],'isolation','elbow_flexion','beginner',false,false,'hammer_curl','{"equipment":"cable","grip":"rope"}'::jsonb),
 ('reverse_curl',true,'Reverse Curls',array['reverse curl']::text[],'isolation','elbow_flexion','beginner',false,false,'hammer_curl','{"equipment":"ez_bar","grip":"overhand"}'::jsonb),
 ('cross_body_hammer_curl',true,'Hammercurls über Kreuz',array['cross body curl']::text[],'isolation','elbow_flexion','beginner',false,false,'hammer_curl','{"equipment":"dumbbell","execution":"cross_body"}'::jsonb),
 ('triceps_pushdown',true,'Trizepsdrücken Stange',array['triceps pushdown','pushdown']::text[],'isolation','elbow_extension','beginner',false,false,'triceps_extension','{"equipment":"cable","grip":"bar"}'::jsonb),
 ('rope_pushdown',true,'Trizepsdrücken Seil',array['rope pushdown']::text[],'isolation','elbow_extension','beginner',false,false,'triceps_extension','{"equipment":"cable","grip":"rope"}'::jsonb),
 ('v_bar_pushdown',true,'Trizepsdrücken V-Griff',array['v-bar pushdown']::text[],'isolation','elbow_extension','beginner',false,false,'triceps_extension','{"equipment":"cable","grip":"v_bar"}'::jsonb),
 ('single_arm_pushdown',true,'Trizepsdrücken einarmig',array[]::text[],'isolation','elbow_extension','beginner',true,false,'triceps_extension','{"equipment":"cable","execution":"single_arm"}'::jsonb),
 ('reverse_grip_pushdown',true,'Trizepsdrücken Untergriff',array[]::text[],'isolation','elbow_extension','beginner',false,false,'triceps_extension','{"equipment":"cable","grip":"underhand"}'::jsonb),
 ('overhead_triceps',true,'Überkopf-Trizeps Kabel',array['overhead cable extension']::text[],'isolation','elbow_extension','beginner',false,false,'triceps_extension','{"equipment":"cable","execution":"overhead"}'::jsonb),
 ('db_overhead_triceps',true,'Überkopf-Trizeps Kurzhantel',array['overhead dumbbell extension','french press']::text[],'isolation','elbow_extension','beginner',false,false,'triceps_extension','{"equipment":"dumbbell","execution":"overhead"}'::jsonb),
 ('skull_crusher',true,'Skull Crusher SZ-Stange',array['skull crusher','lying triceps extension']::text[],'isolation','elbow_extension','intermediate',false,false,'triceps_extension','{"equipment":"ez_bar","execution":"lying"}'::jsonb),
 ('db_skull_crusher',true,'Skull Crusher Kurzhantel',array[]::text[],'isolation','elbow_extension','intermediate',false,false,'triceps_extension','{"equipment":"dumbbell","execution":"lying"}'::jsonb),
 ('triceps_kickback',true,'Trizeps-Kickbacks',array['kickback']::text[],'isolation','elbow_extension','beginner',true,false,'triceps_extension','{"equipment":"dumbbell","execution":"kickback"}'::jsonb),
 ('jm_press',true,'JM Press',array[]::text[],'isolation','elbow_extension','advanced',false,false,'triceps_extension','{"equipment":"barbell","execution":"jm"}'::jsonb),
 ('triceps_machine',true,'Trizepsmaschine',array['triceps machine']::text[],'isolation','elbow_extension','beginner',false,false,'triceps_extension','{"equipment":"machine"}'::jsonb),
 ('wrist_curl',true,'Handgelenkcurls',array['wrist curl']::text[],'isolation','wrist_flexion','beginner',false,false,'wrist','{"equipment":"barbell"}'::jsonb),
 ('reverse_wrist_curl',true,'Handgelenkcurls Obergriff',array['reverse wrist curl']::text[],'isolation','wrist_flexion','beginner',false,false,'wrist','{"equipment":"dumbbell","grip":"overhand"}'::jsonb),
 ('dead_hang',true,'Dead Hang',array['hängen']::text[],'isolation','wrist_flexion','beginner',false,true,'wrist','{"equipment":"bodyweight"}'::jsonb),
 ('crunch',true,'Crunch',array['crunches','sit-up']::text[],'isolation','trunk_flexion','beginner',false,true,'crunch','{"equipment":"bodyweight"}'::jsonb),
 ('cable_crunch',true,'Cable Crunch',array['kneeling cable crunch']::text[],'isolation','trunk_flexion','beginner',false,false,'crunch','{"equipment":"cable","grip":"rope"}'::jsonb),
 ('ab_machine',true,'Bauchmaschine',array['ab machine','ab crunch machine']::text[],'isolation','trunk_flexion','beginner',false,false,'crunch','{"equipment":"machine"}'::jsonb),
 ('decline_crunch',true,'Crunch Negativbank',array['decline sit-up']::text[],'isolation','trunk_flexion','intermediate',false,true,'crunch','{"equipment":"bodyweight","angle":"decline"}'::jsonb),
 ('hanging_leg_raise',true,'Beinheben hängend',array['hanging leg raise','toes to bar']::text[],'isolation','trunk_flexion','intermediate',false,true,'leg_raise','{"equipment":"bodyweight","execution":"hanging"}'::jsonb),
 ('hanging_knee_raise',true,'Knieheben hängend',array['hanging knee raise','captains chair']::text[],'isolation','trunk_flexion','beginner',false,true,'leg_raise','{"equipment":"bodyweight","execution":"hanging_knee"}'::jsonb),
 ('lying_leg_raise',true,'Beinheben liegend',array['lying leg raise']::text[],'isolation','trunk_flexion','beginner',false,true,'leg_raise','{"equipment":"bodyweight","execution":"lying"}'::jsonb),
 ('reverse_crunch',true,'Reverse Crunch',array[]::text[],'isolation','trunk_flexion','beginner',false,true,'leg_raise','{"equipment":"bodyweight"}'::jsonb),
 ('ab_wheel',true,'Ab Wheel',array['ab roller','ab-roller']::text[],'stability','stability','intermediate',false,true,'plank','{"equipment":"bodyweight","execution":"rollout"}'::jsonb),
 ('plank',true,'Plank',array['unterarmstütz','forearm plank']::text[],'stability','stability','beginner',false,true,'plank','{"equipment":"bodyweight"}'::jsonb),
 ('side_plank',true,'Side Plank',array['seitstütz']::text[],'stability','stability','beginner',true,true,'plank','{"equipment":"bodyweight","execution":"side"}'::jsonb),
 ('plank_weighted',true,'Plank mit Zusatzlast',array[]::text[],'stability','stability','intermediate',false,true,'plank','{"equipment":"bodyweight","execution":"weighted"}'::jsonb),
 ('hollow_hold',true,'Hollow Body Hold',array['hollow hold']::text[],'stability','stability','intermediate',false,true,'plank','{"equipment":"bodyweight","execution":"hollow"}'::jsonb),
 ('dead_bug',true,'Dead Bug',array[]::text[],'stability','stability','beginner',false,true,'plank','{"equipment":"bodyweight","execution":"dead_bug"}'::jsonb),
 ('bird_dog',true,'Bird Dog',array[]::text[],'stability','stability','beginner',false,true,'plank','{"equipment":"bodyweight","execution":"bird_dog"}'::jsonb),
 ('pallof_press',true,'Pallof Press',array['pallof']::text[],'stability','anti_rotation','beginner',true,false,'anti_rotation','{"equipment":"cable"}'::jsonb),
 ('cable_woodchop',true,'Woodchop Kabel',array['woodchop','cable chop']::text[],'isolation','rotation','beginner',true,false,'rotation','{"equipment":"cable"}'::jsonb),
 ('russian_twist',true,'Russian Twist',array[]::text[],'isolation','rotation','beginner',false,true,'rotation','{"equipment":"bodyweight"}'::jsonb),
 ('landmine_rotation',true,'Landmine Rotation',array[]::text[],'isolation','rotation','intermediate',false,false,'rotation','{"equipment":"barbell","execution":"landmine"}'::jsonb),
 ('farmer_carry',true,'Farmer’s Walk',array['farmer walk','farmer carry','farmer']::text[],'compound','carry','beginner',false,false,'carry','{"equipment":"dumbbell"}'::jsonb),
 ('suitcase_carry',true,'Suitcase Carry',array[]::text[],'compound','carry','beginner',true,false,'carry','{"equipment":"dumbbell","execution":"single_arm"}'::jsonb),
 ('overhead_carry',true,'Overhead Carry',array[]::text[],'compound','carry','intermediate',false,false,'carry','{"equipment":"dumbbell","execution":"overhead"}'::jsonb),
 ('box_jump',true,'Box Jumps',array['box jump']::text[],'plyometric','jump','intermediate',false,true,'plyo','{"equipment":"bodyweight"}'::jsonb),
 ('broad_jump',true,'Standweitsprung',array['broad jump']::text[],'plyometric','jump','intermediate',false,true,'plyo','{"equipment":"bodyweight"}'::jsonb),
 ('jump_squat',true,'Jump Squats',array['jump squat']::text[],'plyometric','jump','intermediate',false,true,'plyo','{"equipment":"bodyweight"}'::jsonb),
 ('pogo_hops',true,'Pogo Hops',array['pogos']::text[],'plyometric','jump','beginner',false,true,'plyo','{"equipment":"bodyweight"}'::jsonb)
on conflict (slug) do update set
  base_slug = excluded.base_slug,
  variant = excluded.variant,
  movement_pattern = coalesce(public.exercises.movement_pattern, excluded.movement_pattern),
  aliases = case when coalesce(cardinality(public.exercises.aliases), 0) = 0 then excluded.aliases else public.exercises.aliases end;

insert into public.exercise_muscles (exercise_id, muscle_key, weight, involvement)
 select e.id, v.mk, v.w, v.inv from public.exercises e join (values
('bench_press','chest',1,'direct'),
('bench_press','triceps',0.5,'indirect'),
('bench_press','front_delts',0.4,'indirect'),
('db_bench_press','chest',1,'direct'),
('db_bench_press','triceps',0.5,'indirect'),
('db_bench_press','front_delts',0.4,'indirect'),
('smith_bench_press','chest',1,'direct'),
('smith_bench_press','triceps',0.5,'indirect'),
('smith_bench_press','front_delts',0.4,'indirect'),
('close_grip_bench','triceps',1,'direct'),
('close_grip_bench','chest',0.6,'indirect'),
('close_grip_bench','front_delts',0.3,'indirect'),
('floor_press','chest',1,'direct'),
('floor_press','triceps',0.5,'indirect'),
('floor_press','front_delts',0.4,'indirect'),
('incline_bench_press','chest',1,'direct'),
('incline_bench_press','front_delts',0.5,'indirect'),
('incline_bench_press','triceps',0.4,'indirect'),
('db_incline_press','chest',1,'direct'),
('db_incline_press','front_delts',0.5,'indirect'),
('db_incline_press','triceps',0.4,'indirect'),
('smith_incline_press','chest',1,'direct'),
('smith_incline_press','front_delts',0.5,'indirect'),
('smith_incline_press','triceps',0.4,'indirect'),
('incline_press_machine','chest',1,'direct'),
('incline_press_machine','front_delts',0.5,'indirect'),
('incline_press_machine','triceps',0.4,'indirect'),
('decline_bench_press','chest',1,'direct'),
('decline_bench_press','triceps',0.5,'indirect'),
('decline_bench_press','front_delts',0.3,'indirect'),
('db_decline_press','chest',1,'direct'),
('db_decline_press','triceps',0.5,'indirect'),
('db_decline_press','front_delts',0.3,'indirect'),
('chest_press_machine','chest',1,'direct'),
('chest_press_machine','triceps',0.4,'indirect'),
('chest_press_machine','front_delts',0.3,'indirect'),
('chest_press_machine_incline','chest',1,'direct'),
('chest_press_machine_incline','triceps',0.4,'indirect'),
('chest_press_machine_incline','front_delts',0.3,'indirect'),
('cable_chest_press','chest',1,'direct'),
('cable_chest_press','triceps',0.4,'indirect'),
('cable_chest_press','front_delts',0.3,'indirect'),
('cable_chest_press_single','chest',1,'direct'),
('cable_chest_press_single','triceps',0.4,'indirect'),
('cable_chest_press_single','front_delts',0.3,'indirect'),
('pec_deck','chest',1,'direct'),
('pec_deck','front_delts',0.25,'indirect'),
('cable_fly','chest',1,'direct'),
('cable_fly','front_delts',0.25,'indirect'),
('cable_fly_high','chest',1,'direct'),
('cable_fly_high','front_delts',0.25,'indirect'),
('cable_fly_low','chest',1,'direct'),
('cable_fly_low','front_delts',0.4,'indirect'),
('db_fly','chest',1,'direct'),
('db_fly','front_delts',0.25,'indirect'),
('db_incline_fly','chest',1,'direct'),
('db_incline_fly','front_delts',0.25,'indirect'),
('pushup','chest',1,'direct'),
('pushup','triceps',0.5,'indirect'),
('pushup','front_delts',0.4,'indirect'),
('pushup_incline','chest',1,'direct'),
('pushup_incline','triceps',0.5,'indirect'),
('pushup_incline','front_delts',0.4,'indirect'),
('pushup_decline','chest',1,'direct'),
('pushup_decline','triceps',0.5,'indirect'),
('pushup_decline','front_delts',0.4,'indirect'),
('pushup_weighted','chest',1,'direct'),
('pushup_weighted','triceps',0.5,'indirect'),
('pushup_weighted','front_delts',0.4,'indirect'),
('chest_dip','chest',1,'direct'),
('chest_dip','triceps',0.6,'indirect'),
('chest_dip','front_delts',0.3,'indirect'),
('triceps_dip','triceps',1,'direct'),
('triceps_dip','chest',0.5,'indirect'),
('triceps_dip','front_delts',0.3,'indirect'),
('dip_machine','triceps',1,'direct'),
('dip_machine','chest',0.6,'indirect'),
('bench_dip','triceps',1,'direct'),
('bench_dip','chest',0.3,'indirect'),
('overhead_press','front_delts',1,'direct'),
('overhead_press','side_delts',0.5,'indirect'),
('overhead_press','triceps',0.5,'indirect'),
('seated_barbell_press','front_delts',1,'direct'),
('seated_barbell_press','side_delts',0.5,'indirect'),
('seated_barbell_press','triceps',0.5,'indirect'),
('db_shoulder_press','front_delts',1,'direct'),
('db_shoulder_press','side_delts',0.5,'indirect'),
('db_shoulder_press','triceps',0.5,'indirect'),
('arnold_press','front_delts',1,'direct'),
('arnold_press','side_delts',0.5,'indirect'),
('arnold_press','triceps',0.5,'indirect'),
('smith_shoulder_press','front_delts',1,'direct'),
('smith_shoulder_press','side_delts',0.5,'indirect'),
('smith_shoulder_press','triceps',0.5,'indirect'),
('shoulder_press_machine','front_delts',1,'direct'),
('shoulder_press_machine','side_delts',0.5,'indirect'),
('shoulder_press_machine','triceps',0.5,'indirect'),
('landmine_press','front_delts',1,'direct'),
('landmine_press','side_delts',0.5,'indirect'),
('landmine_press','triceps',0.5,'indirect'),
('push_press','front_delts',1,'direct'),
('push_press','side_delts',0.5,'indirect'),
('push_press','triceps',0.5,'indirect'),
('lateral_raise','side_delts',1,'direct'),
('cable_lateral_raise','side_delts',1,'direct'),
('machine_lateral_raise','side_delts',1,'direct'),
('lean_away_lateral_raise','side_delts',1,'direct'),
('front_raise','front_delts',1,'direct'),
('cable_front_raise','front_delts',1,'direct'),
('plate_front_raise','front_delts',1,'direct'),
('reverse_fly','rear_delts',1,'direct'),
('reverse_fly','upper_back',0.4,'indirect'),
('reverse_pec_deck','rear_delts',1,'direct'),
('reverse_pec_deck','upper_back',0.4,'indirect'),
('rear_delt_cable','rear_delts',1,'direct'),
('rear_delt_cable','upper_back',0.4,'indirect'),
('chest_supported_reverse_fly','rear_delts',1,'direct'),
('chest_supported_reverse_fly','upper_back',0.4,'indirect'),
('face_pull','rear_delts',1,'direct'),
('face_pull','upper_back',0.5,'indirect'),
('band_face_pull','rear_delts',1,'direct'),
('band_face_pull','upper_back',0.5,'indirect'),
('upright_row','side_delts',1,'direct'),
('upright_row','traps',0.5,'indirect'),
('upright_row','biceps',0.3,'indirect'),
('cable_upright_row','side_delts',1,'direct'),
('cable_upright_row','traps',0.5,'indirect'),
('cable_upright_row','biceps',0.3,'indirect'),
('barbell_shrug','traps',1,'direct'),
('db_shrug','traps',1,'direct'),
('smith_shrug','traps',1,'direct'),
('trap_bar_shrug','traps',1,'direct'),
('pullup','lats',1,'direct'),
('pullup','biceps',0.5,'indirect'),
('pullup','upper_back',0.4,'indirect'),
('pullup_wide','lats',1,'direct'),
('pullup_wide','biceps',0.5,'indirect'),
('pullup_wide','upper_back',0.4,'indirect'),
('pullup_neutral','lats',1,'direct'),
('pullup_neutral','biceps',0.5,'indirect'),
('pullup_neutral','upper_back',0.4,'indirect'),
('chinup','lats',1,'direct'),
('chinup','biceps',0.7,'indirect'),
('chinup','upper_back',0.4,'indirect'),
('pullup_weighted','lats',1,'direct'),
('pullup_weighted','biceps',0.5,'indirect'),
('pullup_weighted','upper_back',0.4,'indirect'),
('pullup_assisted','lats',1,'direct'),
('pullup_assisted','biceps',0.5,'indirect'),
('pullup_assisted','upper_back',0.4,'indirect'),
('pullup_band','lats',1,'direct'),
('pullup_band','biceps',0.5,'indirect'),
('pullup_band','upper_back',0.4,'indirect'),
('lat_pulldown','lats',1,'direct'),
('lat_pulldown','biceps',0.5,'indirect'),
('lat_pulldown','upper_back',0.4,'indirect'),
('lat_pulldown_close','lats',1,'direct'),
('lat_pulldown_close','biceps',0.5,'indirect'),
('lat_pulldown_close','upper_back',0.4,'indirect'),
('lat_pulldown_neutral','lats',1,'direct'),
('lat_pulldown_neutral','biceps',0.5,'indirect'),
('lat_pulldown_neutral','upper_back',0.4,'indirect'),
('lat_pulldown_underhand','lats',1,'direct'),
('lat_pulldown_underhand','biceps',0.7,'indirect'),
('lat_pulldown_underhand','upper_back',0.4,'indirect'),
('lat_pulldown_single','lats',1,'direct'),
('lat_pulldown_single','biceps',0.5,'indirect'),
('lat_pulldown_single','upper_back',0.4,'indirect'),
('lat_pulldown_machine','lats',1,'direct'),
('lat_pulldown_machine','biceps',0.5,'indirect'),
('lat_pulldown_machine','upper_back',0.4,'indirect'),
('straight_arm_pulldown','lats',1,'direct'),
('straight_arm_pulldown','chest',0.3,'indirect'),
('straight_arm_pulldown','triceps',0.2,'indirect'),
('rope_pullover','lats',1,'direct'),
('rope_pullover','chest',0.3,'indirect'),
('rope_pullover','triceps',0.2,'indirect'),
('db_pullover','lats',1,'direct'),
('db_pullover','chest',0.3,'indirect'),
('db_pullover','triceps',0.2,'indirect'),
('pullover_machine','lats',1,'direct'),
('pullover_machine','chest',0.3,'indirect'),
('pullover_machine','triceps',0.2,'indirect'),
('row','upper_back',1,'direct'),
('row','lats',0.6,'indirect'),
('row','biceps',0.5,'indirect'),
('row','rear_delts',0.4,'indirect'),
('barbell_row','upper_back',1,'direct'),
('barbell_row','lats',0.6,'indirect'),
('barbell_row','biceps',0.5,'indirect'),
('barbell_row','rear_delts',0.4,'indirect'),
('barbell_row_underhand','upper_back',1,'direct'),
('barbell_row_underhand','lats',0.6,'indirect'),
('barbell_row_underhand','biceps',0.5,'indirect'),
('barbell_row_underhand','rear_delts',0.4,'indirect'),
('pendlay_row','upper_back',1,'direct'),
('pendlay_row','lats',0.6,'indirect'),
('pendlay_row','biceps',0.5,'indirect'),
('pendlay_row','rear_delts',0.4,'indirect'),
('db_row','upper_back',1,'direct'),
('db_row','lats',0.6,'indirect'),
('db_row','biceps',0.5,'indirect'),
('db_row','rear_delts',0.4,'indirect'),
('db_row_both','upper_back',1,'direct'),
('db_row_both','lats',0.6,'indirect'),
('db_row_both','biceps',0.5,'indirect'),
('db_row_both','rear_delts',0.4,'indirect'),
('chest_supported_row','upper_back',1,'direct'),
('chest_supported_row','lats',0.6,'indirect'),
('chest_supported_row','biceps',0.5,'indirect'),
('chest_supported_row','rear_delts',0.4,'indirect'),
('seal_row','upper_back',1,'direct'),
('seal_row','lats',0.6,'indirect'),
('seal_row','biceps',0.5,'indirect'),
('seal_row','rear_delts',0.4,'indirect'),
('t_bar_row','upper_back',1,'direct'),
('t_bar_row','lats',0.6,'indirect'),
('t_bar_row','biceps',0.5,'indirect'),
('t_bar_row','rear_delts',0.4,'indirect'),
('t_bar_row_supported','upper_back',1,'direct'),
('t_bar_row_supported','lats',0.6,'indirect'),
('t_bar_row_supported','biceps',0.5,'indirect'),
('t_bar_row_supported','rear_delts',0.4,'indirect'),
('cable_row','upper_back',1,'direct'),
('cable_row','lats',0.6,'indirect'),
('cable_row','biceps',0.5,'indirect'),
('cable_row','rear_delts',0.4,'indirect'),
('cable_row_wide','upper_back',1,'direct'),
('cable_row_wide','lats',0.6,'indirect'),
('cable_row_wide','biceps',0.5,'indirect'),
('cable_row_wide','rear_delts',0.4,'indirect'),
('cable_row_rope','upper_back',1,'direct'),
('cable_row_rope','lats',0.6,'indirect'),
('cable_row_rope','biceps',0.5,'indirect'),
('cable_row_rope','rear_delts',0.4,'indirect'),
('cable_row_single','upper_back',1,'direct'),
('cable_row_single','lats',0.6,'indirect'),
('cable_row_single','biceps',0.5,'indirect'),
('cable_row_single','rear_delts',0.4,'indirect'),
('row_machine','upper_back',1,'direct'),
('row_machine','lats',0.6,'indirect'),
('row_machine','biceps',0.5,'indirect'),
('row_machine','rear_delts',0.4,'indirect'),
('row_machine_high','lats',1,'direct'),
('row_machine_high','upper_back',0.6,'indirect'),
('row_machine_high','biceps',0.5,'indirect'),
('smith_row','upper_back',1,'direct'),
('smith_row','lats',0.6,'indirect'),
('smith_row','biceps',0.5,'indirect'),
('smith_row','rear_delts',0.4,'indirect'),
('inverted_row','upper_back',1,'direct'),
('inverted_row','lats',0.6,'indirect'),
('inverted_row','biceps',0.5,'indirect'),
('inverted_row','rear_delts',0.4,'indirect'),
('meadows_row','upper_back',1,'direct'),
('meadows_row','lats',0.6,'indirect'),
('meadows_row','biceps',0.5,'indirect'),
('meadows_row','rear_delts',0.4,'indirect'),
('squat','quads',1,'direct'),
('squat','glutes',0.6,'indirect'),
('squat','lower_back',0.3,'indirect'),
('low_bar_squat','quads',1,'direct'),
('low_bar_squat','glutes',0.8,'indirect'),
('low_bar_squat','lower_back',0.4,'indirect'),
('low_bar_squat','hamstrings',0.3,'indirect'),
('front_squat','quads',1,'direct'),
('front_squat','glutes',0.5,'indirect'),
('front_squat','abs',0.3,'indirect'),
('smith_squat','quads',1,'direct'),
('smith_squat','glutes',0.6,'indirect'),
('smith_squat','lower_back',0.3,'indirect'),
('goblet_squat','quads',1,'direct'),
('goblet_squat','glutes',0.6,'indirect'),
('goblet_squat','lower_back',0.3,'indirect'),
('sumo_squat','quads',1,'direct'),
('sumo_squat','glutes',0.6,'indirect'),
('sumo_squat','adductors',0.6,'indirect'),
('zercher_squat','quads',1,'direct'),
('zercher_squat','glutes',0.6,'indirect'),
('zercher_squat','lower_back',0.3,'indirect'),
('safety_bar_squat','quads',1,'direct'),
('safety_bar_squat','glutes',0.6,'indirect'),
('safety_bar_squat','lower_back',0.3,'indirect'),
('box_squat','quads',1,'direct'),
('box_squat','glutes',0.6,'indirect'),
('box_squat','lower_back',0.3,'indirect'),
('belt_squat','quads',1,'direct'),
('belt_squat','glutes',0.6,'indirect'),
('belt_squat','lower_back',0.3,'indirect'),
('pendulum_squat','quads',1,'direct'),
('pendulum_squat','glutes',0.6,'indirect'),
('pendulum_squat','lower_back',0.3,'indirect'),
('bodyweight_squat','quads',1,'direct'),
('bodyweight_squat','glutes',0.6,'indirect'),
('bodyweight_squat','lower_back',0.3,'indirect'),
('leg_press','quads',1,'direct'),
('leg_press','glutes',0.5,'indirect'),
('leg_press_horizontal','quads',1,'direct'),
('leg_press_horizontal','glutes',0.5,'indirect'),
('leg_press_single','quads',1,'direct'),
('leg_press_single','glutes',0.5,'indirect'),
('leg_press_high_feet','glutes',1,'direct'),
('leg_press_high_feet','hamstrings',0.6,'indirect'),
('leg_press_high_feet','quads',0.6,'indirect'),
('hack_squat','quads',1,'direct'),
('hack_squat','glutes',0.4,'indirect'),
('reverse_hack_squat','glutes',1,'direct'),
('reverse_hack_squat','quads',0.7,'indirect'),
('reverse_hack_squat','hamstrings',0.4,'indirect'),
('v_squat','quads',1,'direct'),
('v_squat','glutes',0.4,'indirect'),
('sissy_squat','quads',1,'direct'),
('walking_lunge','quads',1,'direct'),
('walking_lunge','glutes',0.6,'indirect'),
('walking_lunge','hamstrings',0.3,'indirect'),
('reverse_lunge','quads',1,'direct'),
('reverse_lunge','glutes',0.6,'indirect'),
('reverse_lunge','hamstrings',0.3,'indirect'),
('forward_lunge','quads',1,'direct'),
('forward_lunge','glutes',0.6,'indirect'),
('forward_lunge','hamstrings',0.3,'indirect'),
('barbell_lunge','quads',1,'direct'),
('barbell_lunge','glutes',0.6,'indirect'),
('barbell_lunge','hamstrings',0.3,'indirect'),
('smith_lunge','quads',1,'direct'),
('smith_lunge','glutes',0.6,'indirect'),
('smith_lunge','hamstrings',0.3,'indirect'),
('lateral_lunge','quads',1,'direct'),
('lateral_lunge','adductors',0.7,'indirect'),
('lateral_lunge','glutes',0.5,'indirect'),
('bulgarian_split_squat','quads',1,'direct'),
('bulgarian_split_squat','glutes',0.6,'indirect'),
('smith_split_squat','quads',1,'direct'),
('smith_split_squat','glutes',0.6,'indirect'),
('split_squat','quads',1,'direct'),
('split_squat','glutes',0.6,'indirect'),
('step_up','quads',1,'direct'),
('step_up','glutes',0.6,'indirect'),
('step_up_barbell','quads',1,'direct'),
('step_up_barbell','glutes',0.6,'indirect'),
('deadlift','glutes',1,'direct'),
('deadlift','hamstrings',1,'direct'),
('deadlift','lower_back',1,'direct'),
('deadlift','upper_back',0.5,'indirect'),
('deadlift','traps',0.4,'indirect'),
('sumo_deadlift','glutes',1,'direct'),
('sumo_deadlift','quads',0.7,'indirect'),
('sumo_deadlift','hamstrings',0.6,'indirect'),
('sumo_deadlift','adductors',0.6,'indirect'),
('sumo_deadlift','lower_back',0.6,'indirect'),
('trap_bar_deadlift','glutes',1,'direct'),
('trap_bar_deadlift','quads',0.8,'indirect'),
('trap_bar_deadlift','hamstrings',0.6,'indirect'),
('trap_bar_deadlift','lower_back',0.6,'indirect'),
('trap_bar_deadlift','traps',0.4,'indirect'),
('deficit_deadlift','glutes',1,'direct'),
('deficit_deadlift','hamstrings',1,'direct'),
('deficit_deadlift','lower_back',1,'direct'),
('deficit_deadlift','upper_back',0.5,'indirect'),
('deficit_deadlift','traps',0.4,'indirect'),
('rack_pull','glutes',1,'direct'),
('rack_pull','lower_back',1,'direct'),
('rack_pull','upper_back',0.6,'indirect'),
('rack_pull','traps',0.6,'indirect'),
('rack_pull','hamstrings',0.4,'indirect'),
('romanian_deadlift','hamstrings',1,'direct'),
('romanian_deadlift','glutes',0.6,'indirect'),
('romanian_deadlift','lower_back',0.4,'indirect'),
('db_rdl','hamstrings',1,'direct'),
('db_rdl','glutes',0.6,'indirect'),
('db_rdl','lower_back',0.4,'indirect'),
('single_leg_rdl','hamstrings',1,'direct'),
('single_leg_rdl','glutes',0.6,'indirect'),
('single_leg_rdl','lower_back',0.4,'indirect'),
('stiff_leg_deadlift','hamstrings',1,'direct'),
('stiff_leg_deadlift','glutes',0.6,'indirect'),
('stiff_leg_deadlift','lower_back',0.4,'indirect'),
('smith_rdl','hamstrings',1,'direct'),
('smith_rdl','glutes',0.6,'indirect'),
('smith_rdl','lower_back',0.4,'indirect'),
('good_morning','hamstrings',1,'direct'),
('good_morning','glutes',0.5,'indirect'),
('good_morning','lower_back',0.6,'indirect'),
('hip_thrust','glutes',1,'direct'),
('hip_thrust','hamstrings',0.4,'indirect'),
('hip_thrust_machine','glutes',1,'direct'),
('hip_thrust_machine','hamstrings',0.4,'indirect'),
('smith_hip_thrust','glutes',1,'direct'),
('smith_hip_thrust','hamstrings',0.4,'indirect'),
('single_leg_hip_thrust','glutes',1,'direct'),
('single_leg_hip_thrust','hamstrings',0.4,'indirect'),
('glute_bridge','glutes',1,'direct'),
('glute_bridge','hamstrings',0.4,'indirect'),
('cable_pull_through','glutes',1,'direct'),
('cable_pull_through','hamstrings',0.6,'indirect'),
('kettlebell_swing','glutes',1,'direct'),
('kettlebell_swing','hamstrings',0.7,'indirect'),
('kettlebell_swing','lower_back',0.4,'indirect'),
('back_extension','lower_back',1,'direct'),
('back_extension','glutes',0.6,'indirect'),
('back_extension','hamstrings',0.5,'indirect'),
('back_extension_machine','lower_back',1,'direct'),
('back_extension_machine','glutes',0.6,'indirect'),
('back_extension_machine','hamstrings',0.5,'indirect'),
('reverse_hyper','glutes',1,'direct'),
('reverse_hyper','hamstrings',0.6,'indirect'),
('reverse_hyper','lower_back',0.5,'indirect'),
('seated_leg_curl','hamstrings',1,'direct'),
('lying_leg_curl','hamstrings',1,'direct'),
('leg_curl','hamstrings',1,'direct'),
('standing_leg_curl','hamstrings',1,'direct'),
('nordic_curl','hamstrings',1,'direct'),
('slider_leg_curl','hamstrings',1,'direct'),
('leg_extension','quads',1,'direct'),
('leg_extension_single','quads',1,'direct'),
('standing_calf_raise','calves',1,'direct'),
('seated_calf_raise','calves',1,'direct'),
('calf_raise','calves',1,'direct'),
('leg_press_calf_raise','calves',1,'direct'),
('smith_calf_raise','calves',1,'direct'),
('single_leg_calf_raise','calves',1,'direct'),
('adductor_machine','adductors',1,'direct'),
('cable_adduction','adductors',1,'direct'),
('copenhagen_plank','adductors',1,'direct'),
('copenhagen_plank','abs',0.5,'indirect'),
('abductor_machine','abductors',1,'direct'),
('abductor_machine','glutes',0.5,'indirect'),
('cable_abduction','abductors',1,'direct'),
('cable_abduction','glutes',0.5,'indirect'),
('band_abduction','abductors',1,'direct'),
('band_abduction','glutes',0.5,'indirect'),
('cable_kickback','glutes',1,'direct'),
('glute_kickback_machine','glutes',1,'direct'),
('biceps_curl','biceps',1,'direct'),
('biceps_curl','forearms',0.3,'indirect'),
('db_curl','biceps',1,'direct'),
('db_curl','forearms',0.3,'indirect'),
('barbell_curl','biceps',1,'direct'),
('barbell_curl','forearms',0.3,'indirect'),
('ez_bar_curl','biceps',1,'direct'),
('ez_bar_curl','forearms',0.3,'indirect'),
('incline_curl','biceps',1,'direct'),
('incline_curl','forearms',0.3,'indirect'),
('cable_curl','biceps',1,'direct'),
('cable_curl','forearms',0.3,'indirect'),
('cable_curl_rope','biceps',1,'direct'),
('cable_curl_rope','forearms',0.3,'indirect'),
('bayesian_curl','biceps',1,'direct'),
('bayesian_curl','forearms',0.3,'indirect'),
('preacher_curl','biceps',1,'direct'),
('preacher_curl','forearms',0.3,'indirect'),
('preacher_curl_machine','biceps',1,'direct'),
('preacher_curl_machine','forearms',0.3,'indirect'),
('spider_curl','biceps',1,'direct'),
('spider_curl','forearms',0.3,'indirect'),
('concentration_curl','biceps',1,'direct'),
('concentration_curl','forearms',0.3,'indirect'),
('drag_curl','biceps',1,'direct'),
('drag_curl','forearms',0.3,'indirect'),
('hammer_curl','biceps',1,'direct'),
('hammer_curl','forearms',0.6,'indirect'),
('cable_hammer_curl','biceps',1,'direct'),
('cable_hammer_curl','forearms',0.6,'indirect'),
('reverse_curl','forearms',1,'direct'),
('reverse_curl','biceps',0.5,'indirect'),
('cross_body_hammer_curl','biceps',1,'direct'),
('cross_body_hammer_curl','forearms',0.6,'indirect'),
('triceps_pushdown','triceps',1,'direct'),
('rope_pushdown','triceps',1,'direct'),
('v_bar_pushdown','triceps',1,'direct'),
('single_arm_pushdown','triceps',1,'direct'),
('reverse_grip_pushdown','triceps',1,'direct'),
('overhead_triceps','triceps',1,'direct'),
('db_overhead_triceps','triceps',1,'direct'),
('skull_crusher','triceps',1,'direct'),
('db_skull_crusher','triceps',1,'direct'),
('triceps_kickback','triceps',1,'direct'),
('jm_press','triceps',1,'direct'),
('triceps_machine','triceps',1,'direct'),
('wrist_curl','forearms',1,'direct'),
('reverse_wrist_curl','forearms',1,'direct'),
('dead_hang','forearms',1,'direct'),
('dead_hang','lats',0.3,'indirect'),
('crunch','abs',1,'direct'),
('cable_crunch','abs',1,'direct'),
('ab_machine','abs',1,'direct'),
('decline_crunch','abs',1,'direct'),
('hanging_leg_raise','abs',1,'direct'),
('hanging_leg_raise','hip_flexors',0.6,'indirect'),
('hanging_knee_raise','abs',1,'direct'),
('hanging_knee_raise','hip_flexors',0.6,'indirect'),
('lying_leg_raise','abs',1,'direct'),
('lying_leg_raise','hip_flexors',0.6,'indirect'),
('reverse_crunch','abs',1,'direct'),
('reverse_crunch','hip_flexors',0.6,'indirect'),
('ab_wheel','abs',1,'direct'),
('ab_wheel','lats',0.3,'indirect'),
('plank','abs',1,'direct'),
('side_plank','abs',1,'direct'),
('plank_weighted','abs',1,'direct'),
('hollow_hold','abs',1,'direct'),
('dead_bug','abs',1,'direct'),
('bird_dog','abs',1,'direct'),
('bird_dog','lower_back',0.5,'indirect'),
('bird_dog','glutes',0.4,'indirect'),
('pallof_press','abs',1,'direct'),
('cable_woodchop','abs',1,'direct'),
('russian_twist','abs',1,'direct'),
('landmine_rotation','abs',1,'direct'),
('farmer_carry','forearms',1,'direct'),
('farmer_carry','traps',0.6,'indirect'),
('farmer_carry','abs',0.5,'indirect'),
('suitcase_carry','abs',1,'direct'),
('suitcase_carry','forearms',0.8,'indirect'),
('suitcase_carry','traps',0.4,'indirect'),
('overhead_carry','front_delts',1,'direct'),
('overhead_carry','abs',0.6,'indirect'),
('overhead_carry','traps',0.5,'indirect'),
('box_jump','quads',1,'direct'),
('box_jump','glutes',0.6,'indirect'),
('box_jump','calves',0.5,'indirect'),
('broad_jump','quads',1,'direct'),
('broad_jump','glutes',0.6,'indirect'),
('broad_jump','calves',0.5,'indirect'),
('jump_squat','quads',1,'direct'),
('jump_squat','glutes',0.6,'indirect'),
('jump_squat','calves',0.5,'indirect'),
('pogo_hops','calves',1,'direct'),
('pogo_hops','quads',0.3,'indirect')
 ) as v(slug, mk, w, inv) on e.slug = v.slug
on conflict (exercise_id, muscle_key) do nothing;

insert into public.exercise_equipment (exercise_id, equipment_key)
 select e.id, v.ek from public.exercises e join (values
('bench_press','barbell'),
('bench_press','bench'),
('bench_press','rack'),
('db_bench_press','dumbbell'),
('db_bench_press','bench'),
('smith_bench_press','smith'),
('smith_bench_press','bench'),
('close_grip_bench','barbell'),
('close_grip_bench','bench'),
('close_grip_bench','rack'),
('floor_press','barbell'),
('incline_bench_press','barbell'),
('incline_bench_press','bench'),
('incline_bench_press','rack'),
('db_incline_press','dumbbell'),
('db_incline_press','bench'),
('smith_incline_press','smith'),
('smith_incline_press','bench'),
('incline_press_machine','machine'),
('decline_bench_press','barbell'),
('decline_bench_press','bench'),
('db_decline_press','dumbbell'),
('db_decline_press','bench'),
('chest_press_machine','machine'),
('chest_press_machine_incline','machine'),
('cable_chest_press','cable'),
('cable_chest_press_single','cable'),
('pec_deck','machine'),
('cable_fly','cable'),
('cable_fly_high','cable'),
('cable_fly_low','cable'),
('db_fly','dumbbell'),
('db_fly','bench'),
('db_incline_fly','dumbbell'),
('db_incline_fly','bench'),
('pushup','bodyweight'),
('pushup_incline','bodyweight'),
('pushup_incline','bench'),
('pushup_decline','bodyweight'),
('pushup_decline','bench'),
('pushup_weighted','bodyweight'),
('pushup_weighted','plate'),
('chest_dip','dip_bars'),
('triceps_dip','dip_bars'),
('dip_machine','machine'),
('bench_dip','bench'),
('overhead_press','barbell'),
('overhead_press','rack'),
('seated_barbell_press','barbell'),
('seated_barbell_press','bench'),
('seated_barbell_press','rack'),
('db_shoulder_press','dumbbell'),
('db_shoulder_press','bench'),
('arnold_press','dumbbell'),
('arnold_press','bench'),
('smith_shoulder_press','smith'),
('smith_shoulder_press','bench'),
('shoulder_press_machine','machine'),
('landmine_press','barbell'),
('push_press','barbell'),
('push_press','rack'),
('lateral_raise','dumbbell'),
('cable_lateral_raise','cable'),
('machine_lateral_raise','machine'),
('lean_away_lateral_raise','dumbbell'),
('lean_away_lateral_raise','rack'),
('front_raise','dumbbell'),
('cable_front_raise','cable'),
('plate_front_raise','plate'),
('reverse_fly','dumbbell'),
('reverse_pec_deck','machine'),
('rear_delt_cable','cable'),
('chest_supported_reverse_fly','dumbbell'),
('chest_supported_reverse_fly','bench'),
('face_pull','cable'),
('band_face_pull','band'),
('upright_row','barbell'),
('cable_upright_row','cable'),
('barbell_shrug','barbell'),
('db_shrug','dumbbell'),
('smith_shrug','smith'),
('trap_bar_shrug','trap_bar'),
('pullup','pullup_bar'),
('pullup_wide','pullup_bar'),
('pullup_neutral','pullup_bar'),
('chinup','pullup_bar'),
('pullup_weighted','pullup_bar'),
('pullup_weighted','plate'),
('pullup_assisted','machine'),
('pullup_band','pullup_bar'),
('pullup_band','band'),
('lat_pulldown','cable'),
('lat_pulldown_close','cable'),
('lat_pulldown_neutral','cable'),
('lat_pulldown_underhand','cable'),
('lat_pulldown_single','cable'),
('lat_pulldown_machine','machine'),
('straight_arm_pulldown','cable'),
('rope_pullover','cable'),
('db_pullover','dumbbell'),
('db_pullover','bench'),
('pullover_machine','machine'),
('row','barbell'),
('barbell_row','barbell'),
('barbell_row_underhand','barbell'),
('pendlay_row','barbell'),
('db_row','dumbbell'),
('db_row','bench'),
('db_row_both','dumbbell'),
('chest_supported_row','dumbbell'),
('chest_supported_row','bench'),
('seal_row','barbell'),
('seal_row','bench'),
('t_bar_row','t_bar'),
('t_bar_row_supported','t_bar'),
('cable_row','cable'),
('cable_row_wide','cable'),
('cable_row_rope','cable'),
('cable_row_single','cable'),
('row_machine','machine'),
('row_machine_high','machine'),
('smith_row','smith'),
('inverted_row','smith'),
('inverted_row','rack'),
('meadows_row','barbell'),
('squat','barbell'),
('squat','rack'),
('low_bar_squat','barbell'),
('low_bar_squat','rack'),
('front_squat','barbell'),
('front_squat','rack'),
('smith_squat','smith'),
('goblet_squat','dumbbell'),
('goblet_squat','kettlebell'),
('sumo_squat','dumbbell'),
('sumo_squat','kettlebell'),
('zercher_squat','barbell'),
('zercher_squat','rack'),
('safety_bar_squat','barbell'),
('safety_bar_squat','rack'),
('box_squat','barbell'),
('box_squat','rack'),
('box_squat','box'),
('belt_squat','machine'),
('pendulum_squat','machine'),
('bodyweight_squat','bodyweight'),
('leg_press','leg_press'),
('leg_press_horizontal','machine'),
('leg_press_single','leg_press'),
('leg_press_high_feet','leg_press'),
('hack_squat','machine'),
('reverse_hack_squat','machine'),
('v_squat','machine'),
('sissy_squat','bodyweight'),
('walking_lunge','dumbbell'),
('reverse_lunge','dumbbell'),
('forward_lunge','dumbbell'),
('barbell_lunge','barbell'),
('barbell_lunge','rack'),
('smith_lunge','smith'),
('lateral_lunge','dumbbell'),
('bulgarian_split_squat','dumbbell'),
('bulgarian_split_squat','bench'),
('smith_split_squat','smith'),
('smith_split_squat','bench'),
('split_squat','dumbbell'),
('step_up','dumbbell'),
('step_up','box'),
('step_up_barbell','barbell'),
('step_up_barbell','box'),
('deadlift','barbell'),
('sumo_deadlift','barbell'),
('trap_bar_deadlift','trap_bar'),
('deficit_deadlift','barbell'),
('deficit_deadlift','plate'),
('rack_pull','barbell'),
('rack_pull','rack'),
('romanian_deadlift','barbell'),
('db_rdl','dumbbell'),
('single_leg_rdl','dumbbell'),
('single_leg_rdl','kettlebell'),
('stiff_leg_deadlift','barbell'),
('smith_rdl','smith'),
('good_morning','barbell'),
('good_morning','rack'),
('hip_thrust','barbell'),
('hip_thrust','bench'),
('hip_thrust_machine','machine'),
('smith_hip_thrust','smith'),
('smith_hip_thrust','bench'),
('single_leg_hip_thrust','bench'),
('glute_bridge','bodyweight'),
('cable_pull_through','cable'),
('kettlebell_swing','kettlebell'),
('back_extension','bodyweight'),
('back_extension_machine','machine'),
('reverse_hyper','machine'),
('seated_leg_curl','machine'),
('lying_leg_curl','machine'),
('leg_curl','machine'),
('standing_leg_curl','machine'),
('nordic_curl','bodyweight'),
('slider_leg_curl','bodyweight'),
('leg_extension','machine'),
('leg_extension_single','machine'),
('standing_calf_raise','machine'),
('seated_calf_raise','machine'),
('calf_raise','bodyweight'),
('leg_press_calf_raise','leg_press'),
('smith_calf_raise','smith'),
('single_leg_calf_raise','dumbbell'),
('adductor_machine','machine'),
('cable_adduction','cable'),
('copenhagen_plank','bench'),
('abductor_machine','machine'),
('cable_abduction','cable'),
('band_abduction','band'),
('cable_kickback','cable'),
('glute_kickback_machine','machine'),
('biceps_curl','dumbbell'),
('db_curl','dumbbell'),
('barbell_curl','barbell'),
('ez_bar_curl','ez_bar'),
('incline_curl','dumbbell'),
('incline_curl','bench'),
('cable_curl','cable'),
('cable_curl_rope','cable'),
('bayesian_curl','cable'),
('preacher_curl','ez_bar'),
('preacher_curl','bench'),
('preacher_curl_machine','machine'),
('spider_curl','dumbbell'),
('spider_curl','bench'),
('concentration_curl','dumbbell'),
('drag_curl','barbell'),
('hammer_curl','dumbbell'),
('cable_hammer_curl','cable'),
('reverse_curl','ez_bar'),
('cross_body_hammer_curl','dumbbell'),
('triceps_pushdown','cable'),
('rope_pushdown','cable'),
('v_bar_pushdown','cable'),
('single_arm_pushdown','cable'),
('reverse_grip_pushdown','cable'),
('overhead_triceps','cable'),
('db_overhead_triceps','dumbbell'),
('skull_crusher','ez_bar'),
('skull_crusher','bench'),
('db_skull_crusher','dumbbell'),
('db_skull_crusher','bench'),
('triceps_kickback','dumbbell'),
('jm_press','barbell'),
('jm_press','bench'),
('triceps_machine','machine'),
('wrist_curl','barbell'),
('wrist_curl','bench'),
('reverse_wrist_curl','dumbbell'),
('dead_hang','pullup_bar'),
('crunch','bodyweight'),
('cable_crunch','cable'),
('ab_machine','machine'),
('decline_crunch','bench'),
('hanging_leg_raise','pullup_bar'),
('hanging_knee_raise','pullup_bar'),
('lying_leg_raise','bodyweight'),
('reverse_crunch','bodyweight'),
('ab_wheel','bodyweight'),
('plank','bodyweight'),
('side_plank','bodyweight'),
('plank_weighted','plate'),
('hollow_hold','bodyweight'),
('dead_bug','bodyweight'),
('bird_dog','bodyweight'),
('pallof_press','cable'),
('pallof_press','band'),
('cable_woodchop','cable'),
('russian_twist','bodyweight'),
('russian_twist','plate'),
('landmine_rotation','barbell'),
('farmer_carry','dumbbell'),
('farmer_carry','kettlebell'),
('suitcase_carry','dumbbell'),
('suitcase_carry','kettlebell'),
('overhead_carry','dumbbell'),
('overhead_carry','kettlebell'),
('box_jump','box'),
('broad_jump','open_floor'),
('jump_squat','open_floor'),
('pogo_hops','open_floor')
 ) as v(slug, ek) on e.slug = v.slug
on conflict (exercise_id, equipment_key) do nothing;

insert into public.schema_migrations(version) values ('0047_exercise_catalog_variants') on conflict (version) do nothing;